vehicles_data = {
'A01_T1_Cunningham': {'short_name': 'T1', 'tier': 1, 'type': 'light'}, 
'A02_M2_lt': {'short_name': 'M2 Light', 'tier': 2, 'type': 'light'}, 
'A03_M3_Stuart': {'short_name': 'M3 Stuart', 'tier': 3, 'type': 'light'}, 
'A04_M3_Grant': {'short_name': 'M3 Lee', 'tier': 4, 'type': 'medium'}, 
'A05_M4_Sherman': {'short_name': 'M4', 'tier': 5, 'type': 'medium'}, 
'A06_M4A3E8_Sherman': {'short_name': 'M4A3E8', 'tier': 6, 'type': 'medium'}, 
'A07_T20': {'short_name': 'T20', 'tier': 7, 'type': 'medium'}, 
'A09_T1_hvy': {'short_name': 'T1 Heavy', 'tier': 5, 'type': 'heavy'}, 
'A100_T49': {'short_name': 'T49', 'tier': 9, 'type': 'light'}, 
'A101_M56': {'short_name': 'Scorpion', 'tier': 7, 'type': 'td'}, 
'A102_T28_concept': {'short_name': 'T28 HTC', 'tier': 7, 'type': 'td'}, 
'A103_T71E1': {'short_name': 'T71 DA', 'tier': 7, 'type': 'light'}, 
'A104_M4A3E8A': {'short_name': 'Fury', 'tier': 6, 'type': 'medium'}, 
'A106_M48A2_120': {'short_name': 'M48/T54E2', 'tier': 10, 'type': 'medium'}, 
'A107_T1_HMC': {'short_name': 'T1 HMC', 'tier': 2, 'type': 'spg'}, 
'A108_T18_HMC': {'short_name': 'T18 HMC', 'tier': 3, 'type': 'spg'}, 
'A109_T56_GMC': {'short_name': 'T56 GMC', 'tier': 3, 'type': 'td'}, 
'A10_M6': {'short_name': 'M6', 'tier': 6, 'type': 'heavy'}, 
'A111_T25_Pilot': {'short_name': 'T25 Pilot 1', 'tier': 8, 'type': 'medium'}, 
'A112_T71E2': {'short_name': 'T71 CMCD P', 'tier': 7, 'type': 'light'}, 
'A112_T71E2R': {'short_name': 'T71 CMCD', 'tier': 7, 'type': 'light'}, 
'A115_Chrysler_K': {'short_name': 'Chrysler GF', 'tier': 8, 'type': 'heavy'}, 
'A116_XM551': {'short_name': 'Sheridan', 'tier': 10, 'type': 'light'}, 
'A117_T26E5': {'short_name': 'T26E5', 'tier': 8, 'type': 'heavy'}, 
'A117_T26E5_Patriot': {'short_name': 'T26E5 P', 'tier': 8, 'type': 'heavy'}, 
'A118_M4_Thunderbolt': {'short_name': 'Thunderbolt', 'tier': 6, 'type': 'medium'}, 
'A11_T29': {'short_name': 'T29', 'tier': 7, 'type': 'heavy'}, 
'A120_M48A5': {'short_name': 'M48 Patton', 'tier': 10, 'type': 'medium'}, 
'A12_T32': {'short_name': 'T32', 'tier': 8, 'type': 'heavy'}, 
'A13_T34_hvy': {'short_name': 'T34', 'tier': 8, 'type': 'heavy'}, 
'A13_T34_hvy_BF': {'short_name': 'T34 B', 'tier': 8, 'type': 'heavy'}, 
'A14_T30': {'short_name': 'T30', 'tier': 9, 'type': 'td'}, 
'A15_T57': {'short_name': 'T57', 'tier': 2, 'type': 'spg'}, 
'A16_M7_Priest': {'short_name': 'M7 Priest', 'tier': 3, 'type': 'spg'}, 
'A17_M37': {'short_name': 'M37', 'tier': 4, 'type': 'spg'}, 
'A18_M41': {'short_name': 'M41 HMC', 'tier': 5, 'type': 'spg'}, 
'A19_T2_lt': {'short_name': 'T2 Light', 'tier': 2, 'type': 'light'}, 
'A21_T14': {'short_name': 'T14', 'tier': 5, 'type': 'heavy'}, 
'A22_M5_Stuart': {'short_name': 'M5 Stuart', 'tier': 4, 'type': 'light'}, 
'A23_M7_med': {'short_name': 'M7', 'tier': 5, 'type': 'light'}, 
'A24_T2_med': {'short_name': 'T2 Medium', 'tier': 2, 'type': 'medium'}, 
'A25_M2_med': {'short_name': 'M2 Medium', 'tier': 3, 'type': 'medium'}, 
'A26_T18': {'short_name': 'T18', 'tier': 2, 'type': 'td'}, 
'A27_T82': {'short_name': 'T82 HMC', 'tier': 4, 'type': 'spg'}, 
'A29_T40': {'short_name': 'T40', 'tier': 4, 'type': 'td'}, 
'A30_M10_Wolverine': {'short_name': 'Wolverine', 'tier': 5, 'type': 'td'}, 
'A31_M36_Slagger': {'short_name': 'Jackson', 'tier': 6, 'type': 'td'}, 
'A32_M12': {'short_name': 'M12', 'tier': 7, 'type': 'spg'}, 
'A33_MTLS-1G14': {'short_name': 'MTLS-1G14', 'tier': 3, 'type': 'light'}, 
'A34_M24_Chaffee': {'short_name': 'Chaffee', 'tier': 5, 'type': 'light'}, 
'A35_Pershing': {'short_name': 'Pershing', 'tier': 8, 'type': 'medium'}, 
'A36_Sherman_Jumbo': {'short_name': 'M4A3E2', 'tier': 6, 'type': 'medium'}, 
'A37_M40M43': {'short_name': 'M40/M43', 'tier': 8, 'type': 'spg'}, 
'A38_T92': {'short_name': 'T92 HMC', 'tier': 10, 'type': 'spg'}, 
'A39_T28': {'short_name': 'T28', 'tier': 8, 'type': 'td'}, 
'A40_T95': {'short_name': 'T95', 'tier': 9, 'type': 'td'}, 
'A41_M18_Hellcat': {'short_name': 'Hellcat', 'tier': 6, 'type': 'td'}, 
'A43_M22_Locust': {'short_name': 'Locust', 'tier': 3, 'type': 'light'}, 
'A44_M4A2E4': {'short_name': 'M4A2E4', 'tier': 5, 'type': 'medium'}, 
'A45_M6A2E1': {'short_name': 'M6A2E1', 'tier': 8, 'type': 'heavy'}, 
'A46_T3': {'short_name': 'T3 HMC', 'tier': 2, 'type': 'td'}, 
'A57_M8A1': {'short_name': 'M8A1', 'tier': 4, 'type': 'td'}, 
'A58_T67': {'short_name': 'T67', 'tier': 5, 'type': 'td'}, 
'A62_Ram-II': {'short_name': 'Ram II', 'tier': 5, 'type': 'medium'}, 
'A63_M46_Patton': {'short_name': 'M46 Patton', 'tier': 9, 'type': 'medium'}, 
'A63_M46_Patton_KR': {'short_name': 'M46 KR', 'tier': 8, 'type': 'medium'}, 
'A64_T25_AT': {'short_name': 'T25 AT', 'tier': 7, 'type': 'td'}, 
'A66_M103': {'short_name': 'M103', 'tier': 9, 'type': 'heavy'}, 
'A67_T57_58': {'short_name': 'T57 Heavy', 'tier': 10, 'type': 'heavy'}, 
'A68_T28_Prototype': {'short_name': 'T28 Prot.', 'tier': 8, 'type': 'td'}, 
'A69_T110E5': {'short_name': 'T110E5', 'tier': 10, 'type': 'heavy'}, 
'A71_T21': {'short_name': 'T21', 'tier': 6, 'type': 'light'}, 
'A72_T25_2': {'short_name': 'T25/2', 'tier': 7, 'type': 'td'}, 
'A74_T1_E6': {'short_name': 'T1E6', 'tier': 2, 'type': 'light'}, 
'A78_M4_Improved': {'short_name': 'M4 Improved', 'tier': 5, 'type': 'medium'}, 
'A80_T26_E4_SuperPershing': {'short_name': 'T26E4', 'tier': 8, 'type': 'medium'}, 
'A81_T95_E2': {'short_name': 'T95E2', 'tier': 8, 'type': 'medium'}, 
'A83_T110E4': {'short_name': 'T110E4', 'tier': 10, 'type': 'td'}, 
'A85_T110E3': {'short_name': 'T110E3', 'tier': 10, 'type': 'td'}, 
'A86_T23E3': {'short_name': 'T23E3', 'tier': 7, 'type': 'medium'}, 
'A87_M44': {'short_name': 'M44', 'tier': 6, 'type': 'spg'}, 
'A88_M53_55': {'short_name': 'M53/M55', 'tier': 9, 'type': 'spg'}, 
'A89_T54E1': {'short_name': 'T54E1', 'tier': 9, 'type': 'medium'}, 
'A90_T69': {'short_name': 'T69', 'tier': 8, 'type': 'medium'}, 
'A92_M60': {'short_name': 'M60', 'tier': 10, 'type': 'medium'}, 
'A93_T7_Combat_Car': {'short_name': 'T7 Car', 'tier': 2, 'type': 'light'}, 
'A94_T37': {'short_name': 'T37', 'tier': 6, 'type': 'light'}, 
'A95_T95_E6': {'short_name': 'T95E6', 'tier': 10, 'type': 'medium'}, 
'A97_M41_Bulldog': {'short_name': 'M41 Bulldog', 'tier': 8, 'type': 'light'}, 
'A99_T92_LT': {'short_name': 'T92', 'tier': 8, 'type': 'light'}, 
'Ch01_Type59': {'short_name': 'Type 59', 'tier': 8, 'type': 'medium'}, 
'Ch01_Type59_Gold': {'short_name': 'Type 59 G', 'tier': 8, 'type': 'medium'}, 
'Ch02_Type62': {'short_name': 'Type 62', 'tier': 7, 'type': 'light'}, 
'Ch03_WZ-111': {'short_name': 'WZ-111', 'tier': 8, 'type': 'heavy'}, 
'Ch03_WZ_111_A': {'short_name': 'Alpine Tiger', 'tier': 8, 'type': 'heavy'}, 
'Ch04_T34_1': {'short_name': 'T-34-1', 'tier': 7, 'type': 'medium'}, 
'Ch05_T34_2': {'short_name': 'T-34-2', 'tier': 8, 'type': 'medium'}, 
'Ch06_Renault_NC31': {'short_name': 'NC-31', 'tier': 1, 'type': 'light'}, 
'Ch07_Vickers_MkE_Type_BT26': {'short_name': 'VAE Type B', 'tier': 2, 'type': 'light'}, 
'Ch08_Type97_Chi_Ha': {'short_name': 'Chi-Ha', 'tier': 3, 'type': 'light'}, 
'Ch09_M5': {'short_name': 'M5A1 Stuart', 'tier': 4, 'type': 'light'}, 
'Ch10_IS2': {'short_name': 'IS-2', 'tier': 7, 'type': 'heavy'}, 
'Ch11_110': {'short_name': '110', 'tier': 8, 'type': 'heavy'}, 
'Ch12_111_1_2_3': {'short_name': 'WZ-111 1-4', 'tier': 9, 'type': 'heavy'}, 
'Ch14_T34_3': {'short_name': 'T-34-3', 'tier': 8, 'type': 'medium'}, 
'Ch15_59_16': {'short_name': '59-16', 'tier': 6, 'type': 'light'}, 
'Ch16_WZ_131': {'short_name': 'WZ-131', 'tier': 7, 'type': 'light'}, 
'Ch17_WZ131_1_WZ132': {'short_name': 'WZ-132', 'tier': 8, 'type': 'light'}, 
'Ch18_WZ-120': {'short_name': 'WZ-120', 'tier': 9, 'type': 'medium'}, 
'Ch19_121': {'short_name': '121', 'tier': 10, 'type': 'medium'}, 
'Ch20_Type58': {'short_name': 'Type 58', 'tier': 6, 'type': 'medium'}, 
'Ch21_T34': {'short_name': 'Type T-34', 'tier': 5, 'type': 'medium'}, 
'Ch22_113': {'short_name': '113', 'tier': 10, 'type': 'heavy'}, 
'Ch22_113P': {'short_name': '113', 'tier': 10, 'type': 'heavy'}, 
'Ch22_113_Beijing_Opera': {'short_name': '113 BO', 'tier': 10, 'type': 'heavy'}, 
'Ch23_112': {'short_name': '112', 'tier': 8, 'type': 'heavy'}, 
'Ch24_Type64': {'short_name': 'Type 64', 'tier': 6, 'type': 'light'}, 
'Ch25_121_mod_1971B': {'short_name': '121B', 'tier': 10, 'type': 'medium'}, 
'Ch26_59_Patton': {'short_name': '59-Patton', 'tier': 8, 'type': 'medium'}, 
'Ch28_WZ_132A': {'short_name': 'WZ-132A', 'tier': 9, 'type': 'light'}, 
'Ch29_Type_62C_prot': {'short_name': 'WZ-132-1', 'tier': 10, 'type': 'light'}, 
'Ch30_T-26G_FT': {'short_name': 'T-26G FT', 'tier': 2, 'type': 'td'}, 
'Ch31_M3G_FT': {'short_name': 'M3G FT', 'tier': 3, 'type': 'td'}, 
'Ch32_SU-76G_FT': {'short_name': 'SU-76G FT', 'tier': 4, 'type': 'td'}, 
'Ch33_60G_FT': {'short_name': '60G FT', 'tier': 5, 'type': 'td'}, 
'Ch34_WZ131G_FT': {'short_name': 'WZ-131G FT', 'tier': 6, 'type': 'td'}, 
'Ch35_T-34-2G_FT': {'short_name': 'T-34-2G FT', 'tier': 7, 'type': 'td'}, 
'Ch36_WZ111_1G_FT': {'short_name': 'WZ-111-1 FT', 'tier': 8, 'type': 'td'}, 
'Ch37_WZ111G_FT': {'short_name': 'WZ-111G FT', 'tier': 9, 'type': 'td'}, 
'Ch38_WZ113G_FT': {'short_name': 'WZ-113G FT', 'tier': 10, 'type': 'td'}, 
'Ch39_WZ120_1G_FT': {'short_name': 'WZ-120-1 FT', 'tier': 8, 'type': 'td'}, 
'Ch40_WZ120G_FT': {'short_name': 'WZ-120G FT', 'tier': 9, 'type': 'td'}, 
'Ch41_WZ_111_5A': {'short_name': 'WZ-111 5A', 'tier': 10, 'type': 'heavy'}, 
'Ch41_WZ_111_QL': {'short_name': 'WZ-111 QL', 'tier': 10, 'type': 'heavy'}, 
'Cz01_Skoda_T40': {'short_name': '�koda T 40', 'tier': 6, 'type': 'medium'}, 
'Cz02_TVP_T50': {'short_name': '�koda T 50', 'tier': 9, 'type': 'medium'}, 
'Cz03_LT_vz35': {'short_name': 'LT vz. 35', 'tier': 2, 'type': 'light'}, 
'Cz04_T50_51': {'short_name': 'TVP T 50/51', 'tier': 10, 'type': 'medium'}, 
'Cz05_T34_100': {'short_name': 'T-34/100', 'tier': 7, 'type': 'medium'}, 
'Cz06_Kolohousenka': {'short_name': 'K-housenka', 'tier': 1, 'type': 'light'}, 
'Cz07_TVP_46': {'short_name': 'TVP VTU', 'tier': 8, 'type': 'medium'}, 
'Cz08_T_25': {'short_name': '�koda T 25', 'tier': 6, 'type': 'medium'}, 
'Cz09_T_24': {'short_name': '�koda T 24', 'tier': 5, 'type': 'medium'}, 
'Cz10_LT_vz38': {'short_name': 'LT vz. 38', 'tier': 3, 'type': 'light'}, 
'Cz11_V_8_H': {'short_name': 'ST vz. 39', 'tier': 4, 'type': 'medium'}, 
'F01_RenaultFT': {'short_name': 'FT', 'tier': 1, 'type': 'light'}, 
'F02_D1': {'short_name': 'D1', 'tier': 2, 'type': 'light'}, 
'F03_D2': {'short_name': 'D2', 'tier': 3, 'type': 'medium'}, 
'F04_B1': {'short_name': 'B1', 'tier': 4, 'type': 'heavy'}, 
'F05_BDR_G1B': {'short_name': 'BDR G1 B', 'tier': 5, 'type': 'heavy'}, 
'F06_ARL_44': {'short_name': 'ARL 44', 'tier': 6, 'type': 'heavy'}, 
'F07_AMX_M4_1945': {'short_name': 'AMX M4 45', 'tier': 7, 'type': 'heavy'}, 
'F08_AMX_50_100': {'short_name': 'AMX 50 100', 'tier': 8, 'type': 'heavy'}, 
'F09_AMX_50_120': {'short_name': 'AMX 50 120', 'tier': 9, 'type': 'heavy'}, 
'F10_AMX_50B': {'short_name': 'AMX 50 B', 'tier': 10, 'type': 'heavy'}, 
'F10_AMX_50B_fallout': {'short_name': '(R) AMX 50 B', 'tier': 10, 'type': 'heavy'}, 
'F11_Renault_G1R': {'short_name': 'G1 R', 'tier': 5, 'type': 'medium'}, 
'F12_Hotchkiss_H35': {'short_name': 'H35', 'tier': 2, 'type': 'light'}, 
'F13_AMX38': {'short_name': 'AMX 38', 'tier': 3, 'type': 'light'}, 
'F14_AMX40': {'short_name': 'AMX 40', 'tier': 4, 'type': 'light'}, 
'F15_AMX_12t': {'short_name': 'AMX 12 t', 'tier': 6, 'type': 'light'}, 
'F16_AMX_13_75': {'short_name': 'AMX 13 75', 'tier': 7, 'type': 'light'}, 
'F17_AMX_13_90': {'short_name': 'AMX 13 90', 'tier': 9, 'type': 'light'}, 
'F18_Bat_Chatillon25t': {'short_name': 'B-C 25 t', 'tier': 10, 'type': 'medium'}, 
'F19_Lorraine40t': {'short_name': 'Lorr. 40 t', 'tier': 8, 'type': 'medium'}, 
'F20_RenaultBS': {'short_name': 'FT BS', 'tier': 2, 'type': 'spg'}, 
'F21_Lorraine39_L_AM': {'short_name': 'Lorr. 39L AM', 'tier': 3, 'type': 'spg'}, 
'F22_AMX_105AM': {'short_name': 'AMX 13 AM', 'tier': 5, 'type': 'spg'}, 
'F23_AMX_13F3AM': {'short_name': 'AMX 13 F3', 'tier': 6, 'type': 'spg'}, 
'F24_Lorraine155_50': {'short_name': 'Lorr. 155 50', 'tier': 7, 'type': 'spg'}, 
'F25_Lorraine155_51': {'short_name': 'Lorr. 155 51', 'tier': 8, 'type': 'spg'}, 
'F27_FCM_36Pak40': {'short_name': 'FCM36Pak40', 'tier': 3, 'type': 'td'}, 
'F28_105_leFH18B2': {'short_name': 'leFH18B2', 'tier': 5, 'type': 'spg'}, 
'F30_RenaultFT_AC': {'short_name': 'FT AC', 'tier': 2, 'type': 'td'}, 
'F32_Somua_Sau_40': {'short_name': 'SAu 40', 'tier': 4, 'type': 'td'}, 
'F33_S_35CA': {'short_name': 'S35 CA', 'tier': 5, 'type': 'td'}, 
'F34_ARL_V39': {'short_name': 'ARL V39', 'tier': 6, 'type': 'td'}, 
'F35_AMX_AC_Mle1946': {'short_name': 'AMX AC 46', 'tier': 7, 'type': 'td'}, 
'F36_AMX_AC_Mle1948': {'short_name': 'AMX AC 48', 'tier': 8, 'type': 'td'}, 
'F37_AMX50_Foch': {'short_name': 'Foch', 'tier': 9, 'type': 'td'}, 
'F38_Bat_Chatillon155_58': {'short_name': 'B-C 155 58', 'tier': 10, 'type': 'spg'}, 
'F44_Somua_S35': {'short_name': 'Somua S35', 'tier': 3, 'type': 'medium'}, 
'F49_RenaultR35': {'short_name': 'R35', 'tier': 2, 'type': 'light'}, 
'F50_FCM36_20t': {'short_name': 'FCM 36', 'tier': 2, 'type': 'light'}, 
'F52_RenaultUE57': {'short_name': 'UE 57', 'tier': 3, 'type': 'td'}, 
'F62_ELC_AMX': {'short_name': 'AMX ELC bis', 'tier': 5, 'type': 'light'}, 
'F64_AMX_50Fosh_155': {'short_name': 'Foch 155', 'tier': 10, 'type': 'td'}, 
'F64_AMX_50Fosh_B': {'short_name': 'Foch B', 'tier': 10, 'type': 'td'}, 
'F65_FCM_50t': {'short_name': 'FCM 50 t', 'tier': 8, 'type': 'heavy'}, 
'F66_AMX_Ob_Am105': {'short_name': 'AMX 105 AM', 'tier': 4, 'type': 'spg'}, 
'F67_Bat_Chatillon155_55': {'short_name': 'B-C 155 55', 'tier': 9, 'type': 'spg'}, 
'F68_AMX_Chasseur_de_char_46': {'short_name': 'AMX CDC', 'tier': 8, 'type': 'medium'}, 
'F69_AMX13_57_100': {'short_name': 'AMX 13 57', 'tier': 7, 'type': 'light'}, 
'F69_AMX13_57_100_GrandFinal': {'short_name': 'AMX 13 57F', 'tier': 7, 'type': 'light'}, 
'F70_SARL42': {'short_name': 'SARL 42', 'tier': 4, 'type': 'medium'}, 
'F71_AMX_30_prototype': {'short_name': 'AMX 30', 'tier': 9, 'type': 'medium'}, 
'F72_AMX_30': {'short_name': 'AMX 30 B', 'tier': 10, 'type': 'medium'}, 
'F73_M4A1_Revalorise': {'short_name': 'M4A1 Rev.', 'tier': 8, 'type': 'medium'}, 
'F74_AMX_M4_1949': {'short_name': 'AMX M4 49', 'tier': 8, 'type': 'heavy'}, 
'F74_AMX_M4_1949_Liberte': {'short_name': 'AMX M4 49 L', 'tier': 8, 'type': 'heavy'}, 
'F75_Char_de_25t': {'short_name': 'B-C 25 t AP', 'tier': 9, 'type': 'medium'}, 
'F81_Char_de_65t': {'short_name': 'AMX 65 t', 'tier': 8, 'type': 'heavy'}, 
'F82_AMX_M4_Mle1949_Ter': {'short_name': 'AMX M4 54', 'tier': 10, 'type': 'heavy'}, 
'F83_AMX_M4_Mle1949_Bis': {'short_name': 'AMX M4 51', 'tier': 9, 'type': 'heavy'}, 
'F84_Somua_SM': {'short_name': 'Somua SM', 'tier': 8, 'type': 'heavy'}, 
'F87_Batignolles-Chatillon_12t': {'short_name': 'B-C 12 t', 'tier': 8, 'type': 'light'}, 
'F88_AMX_13_105': {'short_name': 'AMX 13 105', 'tier': 10, 'type': 'light'}, 
'F89_Canon_dassaut_de_105': {'short_name': 'AMX Cda 105', 'tier': 8, 'type': 'td'}, 
'F97_ELC_EVEN_90': {'short_name': 'ELC EVEN 90', 'tier': 8, 'type': 'light'}, 
'F116_Bat_Chatillon_Bourrasque': {'short_name': 'Bourrasque', 'tier': 8, 'type': 'light'}, 
'G02_Hummel': {'short_name': 'Hummel', 'tier': 6, 'type': 'spg'}, 
'G03_PzV_Panther': {'short_name': 'Panther', 'tier': 7, 'type': 'medium'}, 
'G04_PzVI_Tiger_I': {'short_name': 'Tiger I', 'tier': 7, 'type': 'heavy'}, 
'G04_PzVI_Tiger_IA': {'short_name': 'Tiger I L/56', 'tier': 7, 'type': 'heavy'}, 
'G05_StuG_40_AusfG': {'short_name': 'StuG III G', 'tier': 5, 'type': 'td'}, 
'G06_PzII': {'short_name': 'Pz. II', 'tier': 2, 'type': 'light'}, 
'G07_Pz35t': {'short_name': 'Pz. 35 (t)', 'tier': 2, 'type': 'light'}, 
'G08_Pz38t': {'short_name': 'Pz. 38 (t)', 'tier': 3, 'type': 'light'}, 
'G09_Hetzer': {'short_name': 'Hetzer', 'tier': 4, 'type': 'td'}, 
'G100_Gtraktor_Krupp': {'short_name': 'Gr.Tr.', 'tier': 3, 'type': 'medium'}, 
'G101_StuG_III': {'short_name': 'StuG III B', 'tier': 4, 'type': 'td'}, 
'G102_Pz_III': {'short_name': 'Pz. III E', 'tier': 3, 'type': 'light'}, 
'G103_RU_251': {'short_name': 'Ru 251', 'tier': 9, 'type': 'light'}, 
'G104_Stug_IV': {'short_name': 'StuG IV', 'tier': 5, 'type': 'td'}, 
'G105_T-55_NVA_DDR': {'short_name': 'T 55A', 'tier': 9, 'type': 'medium'}, 
'G106_PzKpfwPanther_AusfF': {'short_name': 'Panther 8,8', 'tier': 8, 'type': 'medium'}, 
'G107_PzKpfwIII_AusfK': {'short_name': 'Pz. III K', 'tier': 5, 'type': 'medium'}, 
'G108_PzKpfwII_AusfD': {'short_name': 'Pz. II D', 'tier': 2, 'type': 'light'}, 
'G109_Steyr_WT': {'short_name': 'Steyr WT', 'tier': 7, 'type': 'td'}, 
'G10_PzIII_AusfJ': {'short_name': 'Pz. III J', 'tier': 4, 'type': 'medium'}, 
'G110_Typ_205': {'short_name': 'M�uschen', 'tier': 9, 'type': 'heavy'}, 
'G112_KanonenJagdPanzer': {'short_name': 'KanJPz', 'tier': 8, 'type': 'td'}, 
'G112_KanonenJagdPanzer_105': {'short_name': 'KanJPz 105', 'tier': 8, 'type': 'td'}, 
'G113_SP_I_C': {'short_name': 'SP I C', 'tier': 7, 'type': 'light'}, 
'G114_Rheinmetall_Skorpian': {'short_name': 'Skorpion G', 'tier': 8, 'type': 'td'}, 
'G114_Skorpian': {'short_name': 'Skorpion', 'tier': 8, 'type': 'td'}, 
'G115_Typ_205B': {'short_name': 'VK 100.01 P', 'tier': 8, 'type': 'heavy'}, 
'G115_Typ_205_4_Jun': {'short_name': 'VK 100.01 B', 'tier': 8, 'type': 'heavy'}, 
'G116_Turan_III_prot': {'short_name': 'Tur�n III PT', 'tier': 5, 'type': 'medium'}, 
'G117_Toldi_III': {'short_name': 'Toldi III', 'tier': 3, 'type': 'light'}, 
'G118_VK4503': {'short_name': 'VK 45.03', 'tier': 7, 'type': 'heavy'}, 
'G119_Panzer58': {'short_name': 'Pz. 58', 'tier': 8, 'type': 'medium'}, 
'G119_Panzer58_BF': {'short_name': 'Schwarzpz.58', 'tier': 8, 'type': 'medium'}, 
'G119_Pz58_Mutz': {'short_name': 'Pz. 58 Mutz', 'tier': 8, 'type': 'medium'}, 
'G11_Bison_I': {'short_name': 'Bison', 'tier': 3, 'type': 'spg'}, 
'G120_M41_90': {'short_name': 'M 41 90 mm', 'tier': 8, 'type': 'light'}, 
'G120_M41_90_GrandFinal': {'short_name': 'M 41 90 GF', 'tier': 8, 'type': 'light'}, 
'G121_Grille_15_L63': {'short_name': 'Grille 15', 'tier': 10, 'type': 'td'}, 
'G122_VK6501H': {'short_name': 'VK 65.01 (H)', 'tier': 5, 'type': 'heavy'}, 
'G125_Spz_57_Rh': {'short_name': 'Rhm. Pzw.', 'tier': 10, 'type': 'light'}, 
'G126_HWK_12': {'short_name': 'HWK 12', 'tier': 8, 'type': 'light'}, 
'G12_Ltraktor': {'short_name': 'L.Tr.', 'tier': 1, 'type': 'light'}, 
'G134_PzKpfw_VII': {'short_name': 'Pz.Kpfw. VII', 'tier': 10, 'type': 'heavy'}, 
'G136_Tiger_131': {'short_name': 'Tiger 131', 'tier': 6, 'type': 'heavy'}, 
'G137_PzVI_Tiger_217': {'short_name': 'Tiger 217', 'tier': 6, 'type': 'heavy'}, 
'G138_VK168_02': {'short_name': 'VK 168.01 P', 'tier': 8, 'type': 'heavy'}, 
'G138_VK168_02_Mauerbrecher': {'short_name': 'Mauerbrecher', 'tier': 8, 'type': 'heavy'}, 
'G13_VK3001H': {'short_name': 'VK 30.01 H', 'tier': 5, 'type': 'heavy'}, 
'G15_VK3601H': {'short_name': 'VK 36.01 H', 'tier': 6, 'type': 'heavy'}, 
'G16_PzVIB_Tiger_II': {'short_name': 'Tiger II', 'tier': 8, 'type': 'heavy'}, 
'G16_PzVIB_Tiger_II_F': {'short_name': 'Tiger II (H)', 'tier': 7, 'type': 'heavy'}, 
'G17_JagdPzIV': {'short_name': 'Jg.Pz. IV', 'tier': 6, 'type': 'td'}, 
'G18_JagdPanther': {'short_name': 'JPanther', 'tier': 7, 'type': 'td'}, 
'G19_Wespe': {'short_name': 'Wespe', 'tier': 3, 'type': 'spg'}, 
'G20_Marder_II': {'short_name': 'Marder II', 'tier': 3, 'type': 'td'}, 
'G21_PanzerJager_I': {'short_name': 'Pz.J�g. I', 'tier': 2, 'type': 'td'}, 
'G22_Sturmpanzer_II': {'short_name': 'St.Pz. II', 'tier': 4, 'type': 'spg'}, 
'G23_Grille': {'short_name': 'Grille', 'tier': 5, 'type': 'spg'}, 
'G24_VK3002DB': {'short_name': 'VK 30.02 D', 'tier': 7, 'type': 'medium'}, 
'G25_PzII_Luchs': {'short_name': 'Luchs', 'tier': 4, 'type': 'light'}, 
'G26_VK1602': {'short_name': 'Leopard', 'tier': 5, 'type': 'light'}, 
'G27_VK3001P': {'short_name': 'VK 30.01 P', 'tier': 6, 'type': 'medium'}, 
'G28_PzIII_IV': {'short_name': 'Pz. III/IV', 'tier': 5, 'type': 'medium'}, 
'G32_PzV_PzIV': {'short_name': 'Pz. V/IV', 'tier': 5, 'type': 'medium'}, 
'G32_PzV_PzIV_ausf_Alfa': {'short_name': 'Pz. V/IV A', 'tier': 5, 'type': 'medium'}, 
'G32_PzV_PzIV_ausf_Alfa_CN': {'short_name': 'Pz. V BP A', 'tier': 6, 'type': 'medium'}, 
'G32_PzV_PzIV_CN': {'short_name': 'Pz. V BP', 'tier': 6, 'type': 'medium'}, 
'G33_H39_captured': {'short_name': 'Pz. 38H', 'tier': 2, 'type': 'light'}, 
'G34_S35_captured': {'short_name': 'Pz. S35', 'tier': 3, 'type': 'medium'}, 
'G35_B-1bis_captured': {'short_name': 'Pz. B2', 'tier': 4, 'type': 'heavy'}, 
'G36_PzII_J': {'short_name': 'Pz. II J', 'tier': 3, 'type': 'light'}, 
'G37_Ferdinand': {'short_name': 'Ferdinand', 'tier': 8, 'type': 'td'}, 
'G39_Marder_III': {'short_name': 'Marder 38T', 'tier': 4, 'type': 'td'}, 
'G40_Nashorn': {'short_name': 'Nashorn', 'tier': 6, 'type': 'td'}, 
'G41_DickerMax': {'short_name': 'Dicker Max', 'tier': 6, 'type': 'td'}, 
'G42_Maus': {'short_name': 'Maus', 'tier': 10, 'type': 'heavy'}, 
'G43_Sturer_Emil': {'short_name': 'St. Emil', 'tier': 7, 'type': 'td'}, 
'G44_JagdTiger': {'short_name': 'Jagdtiger', 'tier': 9, 'type': 'td'}, 
'G44_JagdTigerH': {'short_name': 'Jagdtiger (H)', 'tier': 8, 'type': 'td'}, 
'G45_G_Tiger': {'short_name': 'G.W. Tiger', 'tier': 9, 'type': 'spg'}, 
'G46_T-25': {'short_name': 'Pz. T 25', 'tier': 5, 'type': 'medium'}, 
'G48_E-25': {'short_name': 'E 25', 'tier': 7, 'type': 'td'}, 
'G49_G_Panther': {'short_name': 'G.W. Panther', 'tier': 7, 'type': 'spg'}, 
'G50_T-15': {'short_name': 'Pz. T 15', 'tier': 3, 'type': 'light'}, 
'G51_Lowe': {'short_name': 'L�we', 'tier': 8, 'type': 'heavy'}, 
'G52_Pz38_NA': {'short_name': 'Pz. 38 nA', 'tier': 4, 'type': 'light'}, 
'G53_PzI': {'short_name': 'Pz. I', 'tier': 2, 'type': 'light'}, 
'G54_E-50': {'short_name': 'E 50', 'tier': 9, 'type': 'medium'}, 
'G55_E-75': {'short_name': 'E 75', 'tier': 9, 'type': 'heavy'}, 
'G56_E-100': {'short_name': 'E 100', 'tier': 10, 'type': 'heavy'}, 
'G57_PzVI_Tiger_P': {'short_name': 'Tiger (P)', 'tier': 7, 'type': 'heavy'}, 
'G58_VK4502P': {'short_name': 'VK 45.02 B', 'tier': 9, 'type': 'heavy'}, 
'G58_VK4502P7': {'short_name': 'VK 45.02 B7', 'tier': 7, 'type': 'heavy'}, 
'G61_G_E': {'short_name': 'G.W. E 100', 'tier': 10, 'type': 'spg'}, 
'G63_PzI_ausf_C': {'short_name': 'Pz. I C', 'tier': 3, 'type': 'light'}, 
'G64_Panther_II': {'short_name': 'Panther II', 'tier': 8, 'type': 'medium'}, 
'G65_JagdTiger_SdKfz_185': {'short_name': 'JgTig.8,8 cm', 'tier': 8, 'type': 'td'}, 
'G66_VK2801': {'short_name': 'VK 28.01', 'tier': 6, 'type': 'light'}, 
'G67_VK4502A': {'short_name': 'VK 45.02 A', 'tier': 8, 'type': 'heavy'}, 
'G70_PzIV_Hydro': {'short_name': 'Pz. IV hydr.', 'tier': 5, 'type': 'medium'}, 
'G71_JagdPantherII': {'short_name': 'JPanther II', 'tier': 8, 'type': 'td'}, 
'G72_JagdPz_E100': {'short_name': 'Jg.Pz. E 100', 'tier': 10, 'type': 'td'}, 
'G73_E50_Ausf_M': {'short_name': 'E 50 M', 'tier': 10, 'type': 'medium'}, 
'G76_Pz_Sfl_IVc': {'short_name': 'Pz.Sfl. IVc', 'tier': 5, 'type': 'td'}, 
'G77_PzIV_Schmalturm': {'short_name': 'Pz. IV S.', 'tier': 6, 'type': 'medium'}, 
'G78_Panther_M10': {'short_name': 'Panther/M10', 'tier': 7, 'type': 'medium'}, 
'G79_Pz_IV_AusfGH': {'short_name': 'Pz. IV', 'tier': 5, 'type': 'medium'}, 
'G80_Pz_IV_AusfD': {'short_name': 'Pz. IV D', 'tier': 4, 'type': 'medium'}, 
'G81_Pz_IV_AusfH': {'short_name': 'Pz. IV H', 'tier': 5, 'type': 'medium'}, 
'G82_Pz_II_AusfG': {'short_name': 'Pz. II G', 'tier': 3, 'type': 'light'}, 
'G83_Pz_IV_AusfA': {'short_name': 'Pz. IV A', 'tier': 3, 'type': 'medium'}, 
'G85_Aufklarungspanzer_V': {'short_name': 'Aufkl.Pz. V', 'tier': 8, 'type': 'light'}, 
'G85_Auf_Panther': {'short_name': 'Aufkl.Panther', 'tier': 7, 'type': 'light'}, 
'G86_VK2001DB': {'short_name': 'VK 20.01 D', 'tier': 4, 'type': 'medium'}, 
'G87_VK3002DB_V1': {'short_name': 'VK 30.01 D', 'tier': 6, 'type': 'medium'}, 
'G88_Indien_Panzer': {'short_name': 'Indien-Pz.', 'tier': 8, 'type': 'medium'}, 
'G89_Leopard1': {'short_name': 'Leopard 1', 'tier': 10, 'type': 'medium'}, 
'G90_DW_II': {'short_name': 'D.W. 2', 'tier': 4, 'type': 'heavy'}, 
'G91_Pro_Ag_A': {'short_name': 'Leopard PT A', 'tier': 9, 'type': 'medium'}, 
'G92_VK7201': {'short_name': 'VK 72.01 K', 'tier': 10, 'type': 'heavy'}, 
'G93_GW_Mk_VIe': {'short_name': 'G.Pz. Mk. VI', 'tier': 2, 'type': 'spg'}, 
'G94_GW_Tiger_P': {'short_name': 'G.W. Tiger P', 'tier': 8, 'type': 'spg'}, 
'G95_Pz_Sfl_IVb': {'short_name': 'Pz.Sfl. IVb', 'tier': 4, 'type': 'spg'}, 
'G96_VK3002M': {'short_name': 'VK 30.02 M', 'tier': 6, 'type': 'medium'}, 
'G97_Waffentrager_IV': {'short_name': 'WT auf Pz. IV', 'tier': 9, 'type': 'td'}, 
'G98_Waffentrager_E100': {'short_name': 'WT E 100', 'tier': 10, 'type': 'td'}, 
'G98_Waffentrager_E100_P': {'short_name': 'WT E 100 (P)', 'tier': 10, 'type': 'td'}, 
'G99_RhB_Waffentrager': {'short_name': 'Rhm.-B. WT', 'tier': 8, 'type': 'td'}, 
'GB01_Medium_Mark_I': {'short_name': 'Medium I', 'tier': 1, 'type': 'medium'}, 
'GB03_Cruiser_Mk_I': {'short_name': 'Cruiser I', 'tier': 2, 'type': 'light'}, 
'GB04_Valentine': {'short_name': 'Valentine', 'tier': 4, 'type': 'light'}, 
'GB05_Vickers_Medium_Mk_II': {'short_name': 'Medium II', 'tier': 2, 'type': 'medium'}, 
'GB06_Vickers_Medium_Mk_III': {'short_name': 'Medium III', 'tier': 3, 'type': 'medium'}, 
'GB07_Matilda': {'short_name': 'Matilda', 'tier': 4, 'type': 'medium'}, 
'GB08_Churchill_I': {'short_name': 'Churchill I', 'tier': 5, 'type': 'heavy'}, 
'GB09_Churchill_VII': {'short_name': 'Churchill VII', 'tier': 6, 'type': 'heavy'}, 
'GB10_Black_Prince': {'short_name': 'Black Prince', 'tier': 7, 'type': 'heavy'}, 
'GB11_Caernarvon': {'short_name': 'Caernarvon', 'tier': 8, 'type': 'heavy'}, 
'GB12_Conqueror': {'short_name': 'Conqueror', 'tier': 9, 'type': 'heavy'}, 
'GB13_FV215b': {'short_name': 'FV215b', 'tier': 10, 'type': 'heavy'}, 
'GB14_M2': {'short_name': 'M2', 'tier': 2, 'type': 'light'}, 
'GB15_Stuart_I': {'short_name': 'Stuart I-IV', 'tier': 3, 'type': 'light'}, 
'GB17_Grant_I': {'short_name': 'Grant', 'tier': 4, 'type': 'medium'}, 
'GB19_Sherman_Firefly': {'short_name': 'Firefly', 'tier': 6, 'type': 'medium'}, 
'GB20_Crusader': {'short_name': 'Crusader', 'tier': 5, 'type': 'medium'}, 
'GB21_Cromwell': {'short_name': 'Cromwell', 'tier': 6, 'type': 'medium'}, 
'GB22_Comet': {'short_name': 'Comet', 'tier': 7, 'type': 'medium'}, 
'GB23_Centurion': {'short_name': 'Centurion I', 'tier': 8, 'type': 'medium'}, 
'GB24_Centurion_Mk3': {'short_name': 'Centurion 7/1', 'tier': 9, 'type': 'medium'}, 
'GB25_Loyd_Gun_Carriage': {'short_name': 'Loyd GC', 'tier': 2, 'type': 'spg'}, 
'GB26_Birch_Gun': {'short_name': 'Birch Gun', 'tier': 4, 'type': 'spg'}, 
'GB27_Sexton': {'short_name': 'Sexton II', 'tier': 3, 'type': 'spg'}, 
'GB28_Bishop': {'short_name': 'Bishop', 'tier': 5, 'type': 'spg'}, 
'GB29_Crusader_5inch': {'short_name': 'Crusader SP', 'tier': 7, 'type': 'spg'}, 
'GB30_FV3805': {'short_name': 'FV3805', 'tier': 9, 'type': 'spg'}, 
'GB31_Conqueror_Gun': {'short_name': 'ConquerorGC', 'tier': 10, 'type': 'spg'}, 
'GB32_Tortoise': {'short_name': 'Tortoise', 'tier': 9, 'type': 'td'}, 
'GB33_Sentinel_AC_I': {'short_name': 'Sentinel', 'tier': 4, 'type': 'medium'}, 
'GB35_Sentinel_AC_IV': {'short_name': 'AC 4 Exp.', 'tier': 6, 'type': 'medium'}, 
'GB39_Universal_CarrierQF2': {'short_name': 'UC 2-pdr', 'tier': 2, 'type': 'td'}, 
'GB40_Gun_Carrier_Churchill': {'short_name': 'Churchill GC', 'tier': 6, 'type': 'td'}, 
'GB41_Challenger': {'short_name': 'Challenger', 'tier': 7, 'type': 'td'}, 
'GB42_Valentine_AT': {'short_name': 'Valentine AT', 'tier': 3, 'type': 'td'}, 
'GB44_Archer': {'short_name': 'Archer', 'tier': 5, 'type': 'td'}, 
'GB45_Achilles_IIC': {'short_name': 'Achilles', 'tier': 6, 'type': 'td'}, 
'GB48_FV215b_183': {'short_name': 'FV215b 183', 'tier': 10, 'type': 'td'}, 
'GB50_Sherman_III': {'short_name': 'Sherman III', 'tier': 5, 'type': 'medium'}, 
'GB51_Excelsior': {'short_name': 'Excelsior', 'tier': 5, 'type': 'heavy'}, 
'GB52_A45': {'short_name': 'FV201 (A45)', 'tier': 7, 'type': 'heavy'}, 
'GB57_Alecto': {'short_name': 'Alecto', 'tier': 4, 'type': 'td'}, 
'GB58_Cruiser_Mk_III': {'short_name': 'Cruiser III', 'tier': 2, 'type': 'light'}, 
'GB59_Cruiser_Mk_IV': {'short_name': 'Cruiser IV', 'tier': 3, 'type': 'light'}, 
'GB60_Covenanter': {'short_name': 'Covenanter', 'tier': 4, 'type': 'light'}, 
'GB63_TOG_II': {'short_name': 'TOG II*', 'tier': 6, 'type': 'heavy'}, 
'GB68_Matilda_Black_Prince': {'short_name': 'Matilda BP', 'tier': 5, 'type': 'medium'}, 
'GB69_Cruiser_Mk_II': {'short_name': 'Cruiser II', 'tier': 3, 'type': 'light'}, 
'GB70_FV4202_105': {'short_name': 'FV4202', 'tier': 10, 'type': 'medium'}, 
'GB70_N_FV4202_105': {'short_name': 'FV4202', 'tier': 8, 'type': 'medium'}, 
'GB71_AT_15A': {'short_name': 'AT 15A', 'tier': 7, 'type': 'td'}, 
'GB72_AT15': {'short_name': 'AT 15', 'tier': 8, 'type': 'td'}, 
'GB73_AT2': {'short_name': 'AT 2', 'tier': 5, 'type': 'td'}, 
'GB74_AT8': {'short_name': 'AT 8', 'tier': 6, 'type': 'td'}, 
'GB75_AT7': {'short_name': 'AT 7', 'tier': 7, 'type': 'td'}, 
'GB76_Mk_VIC': {'short_name': 'Light VIC', 'tier': 2, 'type': 'light'}, 
'GB77_FV304': {'short_name': 'FV304', 'tier': 6, 'type': 'spg'}, 
'GB78_Sexton_I': {'short_name': 'Sexton I', 'tier': 3, 'type': 'spg'}, 
'GB79_FV206': {'short_name': 'FV207', 'tier': 8, 'type': 'spg'}, 
'GB80_Charioteer': {'short_name': 'Charioteer', 'tier': 8, 'type': 'td'}, 
'GB81_FV4004': {'short_name': 'Conway', 'tier': 9, 'type': 'td'}, 
'GB83_FV4005': {'short_name': 'FV4005', 'tier': 10, 'type': 'td'}, 
'GB84_Chieftain_Mk6': {'short_name': 'Chieftain', 'tier': 10, 'type': 'heavy'}, 
'GB85_Cromwell_Berlin': {'short_name': 'Cromwell B', 'tier': 6, 'type': 'medium'}, 
'GB86_Centurion_Action_X': {'short_name': 'Centurion AX', 'tier': 10, 'type': 'medium'}, 
'GB87_Chieftain_T95_turret': {'short_name': 'Chieftain/T95', 'tier': 8, 'type': 'medium'}, 
'GB88_T95_Chieftain_turret': {'short_name': 'T95/Chieftain', 'tier': 10, 'type': 'heavy'}, 
'GB91_Super_Conqueror': {'short_name': 'S. Conqueror', 'tier': 10, 'type': 'heavy'}, 
'GB92_FV217': {'short_name': 'Badger', 'tier': 10, 'type': 'td'}, 
'GB93_Caernarvon_AX': {'short_name': 'Caernarvon X', 'tier': 8, 'type': 'heavy'}, 
'It13_Progetto_M35_mod_46': {'short_name': 'Progetto 46', 'tier': 8, 'type': 'medium'}, 
'It09_P43_ter': {'short_name': 'P.43 ter', 'tier': 7, 'type': 'medium'}, 
'J01_NC27': {'short_name': 'R. Otsu', 'tier': 1, 'type': 'light'}, 
'J02_Te_Ke': {'short_name': 'Te-Ke', 'tier': 2, 'type': 'light'}, 
'J03_Ha_Go': {'short_name': 'Ha-Go', 'tier': 2, 'type': 'light'}, 
'J04_Ke_Ni': {'short_name': 'Ke-Ni', 'tier': 3, 'type': 'light'}, 
'J05_Ke_Ni_B': {'short_name': 'Ke-Ni Otsu', 'tier': 3, 'type': 'light'}, 
'J06_Ke_Ho': {'short_name': 'Ke-Ho', 'tier': 4, 'type': 'light'}, 
'J07_Chi_Ha': {'short_name': 'Chi-Ha', 'tier': 3, 'type': 'medium'}, 
'J08_Chi_Nu': {'short_name': 'Chi-Nu', 'tier': 5, 'type': 'medium'}, 
'J09_Chi_He': {'short_name': 'Chi-He', 'tier': 4, 'type': 'medium'}, 
'J10_Chi_To': {'short_name': 'Chi-To', 'tier': 6, 'type': 'medium'}, 
'J11_Chi_Ri': {'short_name': 'Chi-Ri', 'tier': 7, 'type': 'medium'}, 
'J12_Chi_Nu_Kai': {'short_name': 'Chi-Nu Kai', 'tier': 5, 'type': 'medium'}, 
'J13_STA_1': {'short_name': 'STA-1', 'tier': 8, 'type': 'medium'}, 
'J14_Type_61': {'short_name': 'Type 61', 'tier': 9, 'type': 'medium'}, 
'J15_Chi_Ni': {'short_name': 'Chi-Ni', 'tier': 2, 'type': 'medium'}, 
'J16_ST_B1': {'short_name': 'STB-1', 'tier': 10, 'type': 'medium'}, 
'J18_STA_2_3': {'short_name': 'STA-2', 'tier': 8, 'type': 'medium'}, 
'J19_Tiger_I_Jpn': {'short_name': 'HT No. VI', 'tier': 6, 'type': 'heavy'}, 
'J20_Type_2605': {'short_name': 'Type 5 Heavy', 'tier': 10, 'type': 'heavy'}, 
'J21_Type_91': {'short_name': 'Type 91', 'tier': 3, 'type': 'heavy'}, 
'J22_Type_95': {'short_name': 'Type 95', 'tier': 4, 'type': 'heavy'}, 
'J23_Mi_To': {'short_name': 'O-I Exp.', 'tier': 5, 'type': 'heavy'}, 
'J24_Mi_To_130_tons': {'short_name': 'O-I', 'tier': 6, 'type': 'heavy'}, 
'J25_Type_4': {'short_name': 'Type 4 Heavy', 'tier': 9, 'type': 'heavy'}, 
'J26_Type_89': {'short_name': 'I-Go/Chi-Ro', 'tier': 2, 'type': 'medium'}, 
'J27_O_I_120': {'short_name': 'O-Ho', 'tier': 8, 'type': 'heavy'}, 
'J28_O_I_100': {'short_name': 'O-Ni', 'tier': 7, 'type': 'heavy'}, 
'J29_Nameless': {'short_name': 'Nameless', 'tier': 8, 'type': 'heavy'}, 
'J30_Edelweiss': {'short_name': 'Edelweiss', 'tier': 8, 'type': 'medium'}, 
'Pl03_PzV_Poland': {'short_name': 'Pudel', 'tier': 6, 'type': 'medium'}, 
'R01_IS': {'short_name': 'IS', 'tier': 7, 'type': 'heavy'}, 
'R02_SU-85': {'short_name': 'SU-85', 'tier': 5, 'type': 'td'}, 
'R03_BT-7': {'short_name': 'BT-7', 'tier': 3, 'type': 'light'}, 
'R04_T-34': {'short_name': 'T-34', 'tier': 5, 'type': 'medium'}, 
'R05_KV': {'short_name': 'KV', 'tier': 5, 'type': 'heavy'}, 
'R06_T-28': {'short_name': 'T-28', 'tier': 4, 'type': 'medium'}, 
'R07_T-34-85': {'short_name': 'T-34-85', 'tier': 6, 'type': 'medium'}, 
'R08_BT-2': {'short_name': 'BT-2', 'tier': 2, 'type': 'light'}, 
'R09_T-26': {'short_name': 'T-26', 'tier': 2, 'type': 'light'}, 
'R100_SU122A': {'short_name': 'SU-122A', 'tier': 5, 'type': 'spg'}, 
'R101_MT25': {'short_name': 'MT-25', 'tier': 6, 'type': 'light'}, 
'R104_Object_430_II': {'short_name': 'Obj. 430 II', 'tier': 9, 'type': 'medium'}, 
'R105_BT_7A': {'short_name': 'BT-7 art.', 'tier': 3, 'type': 'light'}, 
'R106_KV85': {'short_name': 'KV-85', 'tier': 6, 'type': 'heavy'}, 
'R107_LTB': {'short_name': 'LTTB', 'tier': 8, 'type': 'light'}, 
'R108_T34_85M': {'short_name': 'T-34-85M', 'tier': 6, 'type': 'medium'}, 
'R109_T54S': {'short_name': 'T-54 ltwt.', 'tier': 9, 'type': 'light'}, 
'R10_AT-1': {'short_name': 'AT-1', 'tier': 2, 'type': 'td'}, 
'R110_Object_260': {'short_name': 'Obj. 260', 'tier': 10, 'type': 'heavy'}, 
'R111_ISU130': {'short_name': 'ISU-130', 'tier': 8, 'type': 'td'}, 
'R112_T54_45': {'short_name': 'T-54 mod. 1', 'tier': 8, 'type': 'medium'}, 
'R113_Object_730': {'short_name': 'IS-5', 'tier': 8, 'type': 'heavy'}, 
'R114_Object_244': {'short_name': 'Obj. 244', 'tier': 6, 'type': 'heavy'}, 
'R115_IS-3_auto': {'short_name': 'IS-3A', 'tier': 8, 'type': 'heavy'}, 
'R116_ISU122C_Berlin': {'short_name': 'ISU-122S', 'tier': 7, 'type': 'td'}, 
'R117_T34_85_Rudy': {'short_name': 'Rudy', 'tier': 6, 'type': 'medium'}, 
'R118_T28_F30': {'short_name': 'T-28E F-30', 'tier': 4, 'type': 'medium'}, 
'R119_Object_777': {'short_name': 'Obj. 777 II', 'tier': 10, 'type': 'heavy'}, 
'R11_MS-1': {'short_name': 'MS-1', 'tier': 1, 'type': 'light'}, 
'R120_T22SR_A22': {'short_name': 'T-22 med.', 'tier': 10, 'type': 'medium'}, 
'R121_KV4_KTT': {'short_name': 'KV-4 KTTS', 'tier': 8, 'type': 'td'}, 
'R122_T44_100': {'short_name': 'T-44-100', 'tier': 8, 'type': 'medium'}, 
'R122_T44_100B': {'short_name': 'T-44-100M', 'tier': 8, 'type': 'medium'}, 
'R123_Kirovets_1': {'short_name': 'Kirovets-1', 'tier': 8, 'type': 'heavy'}, 
'R125_T_45': {'short_name': 'T-45', 'tier': 2, 'type': 'light'}, 
'R126_Object_730_5': {'short_name': 'Obj. 268 5', 'tier': 10, 'type': 'td'}, 
'R127_T44_100_P': {'short_name': 'T-44-100 (R)', 'tier': 8, 'type': 'medium'}, 
'R128_KV4_Kreslavskiy': {'short_name': 'KV-4 Kresl.', 'tier': 8, 'type': 'heavy'}, 
'R129_Object_257': {'short_name': 'Obj. 257 P', 'tier': 10, 'type': 'heavy'}, 
'R12_A-20': {'short_name': 'A-20', 'tier': 4, 'type': 'light'}, 
'R131_Tank_Gavalov': {'short_name': 'LTG', 'tier': 7, 'type': 'light'}, 
'R132_VNII_100LT': {'short_name': 'T-100 LT', 'tier': 10, 'type': 'light'}, 
'R133_KV_122': {'short_name': 'KV-122', 'tier': 7, 'type': 'heavy'}, 
'R134_Object_252K': {'short_name': 'Defender', 'tier': 8, 'type': 'heavy'}, 
'R134_Object_252U': {'short_name': 'Obj. 252U', 'tier': 8, 'type': 'heavy'}, 
'R135_T_103': {'short_name': 'T-103', 'tier': 8, 'type': 'td'}, 
'R139_IS_2_Sh': {'short_name': 'IS-M', 'tier': 8, 'type': 'heavy'}, 
'R13_KV-1s': {'short_name': 'KV-1S', 'tier': 5, 'type': 'heavy'}, 
'R140_M4_Loza': {'short_name': "Loza's M4-A2", 'tier': 6, 'type': 'medium'}, 
'R143_T_29': {'short_name': 'T-29', 'tier': 3, 'type': 'medium'}, 
'R145_Object_705_A': {'short_name': 'Obj. 705A', 'tier': 10, 'type': 'heavy'}, 
'R146_STG': {'short_name': 'STG', 'tier': 8, 'type': 'medium'}, 
'R146_STG_Tday': {'short_name': 'Guard', 'tier': 8, 'type': 'medium'}, 
'R148_Object_430_U': {'short_name': 'Obj. 430U', 'tier': 10, 'type': 'medium'}, 
'R149_Object_268_4': {'short_name': 'Obj. 268 4', 'tier': 10, 'type': 'td'}, 
'R14_SU-5': {'short_name': 'SU-5', 'tier': 4, 'type': 'spg'}, 
'R151_Object_257_2': {'short_name': 'Obj. 257', 'tier': 9, 'type': 'heavy'}, 
'R153_Object_705': {'short_name': 'Obj. 705', 'tier': 9, 'type': 'heavy'}, 
'R165_Object_703_II': {'short_name': '703 II (122)', 'tier': 8, 'type': 'heavy'}, 
'R15_S-51': {'short_name': 'S-51', 'tier': 7, 'type': 'spg'}, 
'R16_SU-18': {'short_name': 'SU-18', 'tier': 2, 'type': 'spg'}, 
'R17_SU-100': {'short_name': 'SU-100', 'tier': 6, 'type': 'td'}, 
'R18_SU-152': {'short_name': 'SU-152', 'tier': 7, 'type': 'td'}, 
'R19_IS-3': {'short_name': 'IS-3', 'tier': 8, 'type': 'heavy'}, 
'R20_T-44': {'short_name': 'T-44', 'tier': 8, 'type': 'medium'}, 
'R22_T-46': {'short_name': 'T-46', 'tier': 3, 'type': 'light'}, 
'R23_T-43': {'short_name': 'T-43', 'tier': 7, 'type': 'medium'}, 
'R24_SU-76': {'short_name': 'SU-76M', 'tier': 3, 'type': 'td'}, 
'R25_GAZ-74b': {'short_name': 'SU-85B', 'tier': 4, 'type': 'td'}, 
'R26_SU-8': {'short_name': 'SU-8', 'tier': 6, 'type': 'spg'}, 
'R27_SU-14': {'short_name': 'SU-14-2', 'tier': 8, 'type': 'spg'}, 
'R31_Valentine_LL': {'short_name': 'Valentine II', 'tier': 4, 'type': 'light'}, 
'R32_Matilda_II_LL': {'short_name': 'Matilda IV', 'tier': 5, 'type': 'medium'}, 
'R33_Churchill_LL': {'short_name': 'Churchill III', 'tier': 5, 'type': 'heavy'}, 
'R34_BT-SV': {'short_name': 'BT-SV', 'tier': 3, 'type': 'light'}, 
'R38_KV-220': {'short_name': 'KV-220-2', 'tier': 5, 'type': 'heavy'}, 
'R38_KV-220_beta': {'short_name': 'KV-220-2 T', 'tier': 5, 'type': 'heavy'}, 
'R39_KV-3': {'short_name': 'KV-3', 'tier': 7, 'type': 'heavy'}, 
'R40_T-54': {'short_name': 'T-54', 'tier': 9, 'type': 'medium'}, 
'R41_T-50': {'short_name': 'T-50', 'tier': 5, 'type': 'light'}, 
'R42_T-60': {'short_name': 'T-60', 'tier': 2, 'type': 'light'}, 
'R43_T-70': {'short_name': 'T-70', 'tier': 3, 'type': 'light'}, 
'R44_T80': {'short_name': 'T-80', 'tier': 4, 'type': 'light'}, 
'R45_IS-7': {'short_name': 'IS-7', 'tier': 10, 'type': 'heavy'}, 
'R45_IS-7_fallout': {'short_name': '(R) IS-7', 'tier': 10, 'type': 'heavy'}, 
'R46_KV-13': {'short_name': 'KV-13', 'tier': 7, 'type': 'medium'}, 
'R47_ISU-152': {'short_name': 'ISU-152', 'tier': 8, 'type': 'td'}, 
'R49_SU100Y': {'short_name': 'SU-100Y', 'tier': 6, 'type': 'td'}, 
'R50_SU76I': {'short_name': 'SU-76I', 'tier': 3, 'type': 'td'}, 
'R51_Object_212': {'short_name': '212A', 'tier': 9, 'type': 'spg'}, 
'R52_Object_261': {'short_name': 'Obj. 261', 'tier': 10, 'type': 'spg'}, 
'R53_Object_704': {'short_name': 'Obj. 704', 'tier': 9, 'type': 'td'}, 
'R54_KV-5': {'short_name': 'KV-5', 'tier': 8, 'type': 'heavy'}, 
'R56_T-127': {'short_name': 'T-127', 'tier': 3, 'type': 'light'}, 
'R57_A43': {'short_name': 'A-43', 'tier': 6, 'type': 'medium'}, 
'R58_SU-101': {'short_name': 'SU-101', 'tier': 8, 'type': 'td'}, 
'R59_A44': {'short_name': 'A-44', 'tier': 7, 'type': 'medium'}, 
'R60_Object416': {'short_name': 'Obj. 416', 'tier': 8, 'type': 'medium'}, 
'R61_Object252': {'short_name': 'IS-6', 'tier': 8, 'type': 'heavy'}, 
'R61_Object252_BF': {'short_name': 'IS-6 B', 'tier': 8, 'type': 'heavy'}, 
'R63_ST_I': {'short_name': 'ST-I', 'tier': 9, 'type': 'heavy'}, 
'R66_SU-26': {'short_name': 'SU-26', 'tier': 3, 'type': 'spg'}, 
'R67_M3_LL': {'short_name': 'M3 Light', 'tier': 3, 'type': 'light'}, 
'R68_A-32': {'short_name': 'A-32', 'tier': 4, 'type': 'medium'}, 
'R70_T_50_2': {'short_name': 'T-50-2', 'tier': 5, 'type': 'light'}, 
'R71_IS_2B': {'short_name': 'IS-2', 'tier': 7, 'type': 'heavy'}, 
'R72_T150': {'short_name': 'T-150', 'tier': 6, 'type': 'heavy'}, 
'R73_KV4': {'short_name': 'KV-4', 'tier': 8, 'type': 'heavy'}, 
'R74_SU100M1': {'short_name': 'SU-100M1', 'tier': 7, 'type': 'td'}, 
'R75_SU122_54': {'short_name': 'SU-122-54', 'tier': 9, 'type': 'td'}, 
'R77_KV2': {'short_name': 'KV-2', 'tier': 6, 'type': 'heavy'}, 
'R78_SU_85I': {'short_name': 'SU-85I', 'tier': 5, 'type': 'td'}, 
'R80_KV1': {'short_name': 'KV-1', 'tier': 5, 'type': 'heavy'}, 
'R81_IS8': {'short_name': 'T-10', 'tier': 9, 'type': 'heavy'}, 
'R84_Tetrarch_LL': {'short_name': 'Tetrarch', 'tier': 2, 'type': 'light'}, 
'R86_LTP': {'short_name': 'LTP', 'tier': 3, 'type': 'light'}, 
'R87_T62A': {'short_name': 'T-62A', 'tier': 10, 'type': 'medium'}, 
'R87_T62A_fallout': {'short_name': '(R) T-62A', 'tier': 10, 'type': 'medium'}, 
'R88_Object268': {'short_name': 'Obj. 268', 'tier': 10, 'type': 'td'}, 
'R89_SU122_44': {'short_name': 'SU-122-44', 'tier': 7, 'type': 'td'}, 
'R90_IS_4M': {'short_name': 'IS-4', 'tier': 10, 'type': 'heavy'}, 
'R91_SU14_1': {'short_name': 'SU-14-1', 'tier': 7, 'type': 'spg'}, 
'R93_Object263': {'short_name': 'Obj. 263', 'tier': 9, 'type': 'td'}, 
'R93_Object263B': {'short_name': 'Obj. 263B', 'tier': 10, 'type': 'td'}, 
'R95_Object_907': {'short_name': 'Obj. 907', 'tier': 10, 'type': 'medium'}, 
'R95_Object_907A': {'short_name': 'Obj. 907A', 'tier': 10, 'type': 'medium'}, 
'R96_Object_430': {'short_name': 'Obj. 430', 'tier': 9, 'type': 'medium'}, 
'R96_Object_430B': {'short_name': 'Obj. 430B', 'tier': 10, 'type': 'medium'}, 
'R97_Object_140': {'short_name': 'Obj. 140', 'tier': 10, 'type': 'medium'}, 
'R98_T44_85': {'short_name': 'T-44-85', 'tier': 7, 'type': 'medium'}, 
'R98_T44_85M': {'short_name': 'T-44 ltwt.', 'tier': 8, 'type': 'light'}, 
'R99_T44_122': {'short_name': 'T-44-122', 'tier': 7, 'type': 'medium'}, 
'S01_Strv_74_A2': {'short_name': 'Strv m/42-57', 'tier': 6, 'type': 'medium'}, 
'S02_Strv_M42': {'short_name': 'Strv m/42', 'tier': 5, 'type': 'medium'}, 
'S03_Strv_M38': {'short_name': 'Strv m/38', 'tier': 2, 'type': 'light'}, 
'S04_Lago_I': {'short_name': 'Lago', 'tier': 4, 'type': 'medium'}, 
'S05_Strv_M21_29': {'short_name': 'Strv fm/21', 'tier': 1, 'type': 'light'}, 
'S06_Ikv_90_Typ_B_Bofors': {'short_name': 'Ikv 90 B', 'tier': 7, 'type': 'td'}, 
'S07_Strv_74': {'short_name': 'Strv 74', 'tier': 6, 'type': 'medium'}, 
'S08_Ikv_65_Alt_2': {'short_name': 'Ikv 65 II', 'tier': 6, 'type': 'td'}, 
'S09_L_120_TD': {'short_name': 'Pvlvv fm/42', 'tier': 2, 'type': 'td'}, 
'S10_Strv_103_0_Series': {'short_name': 'Strv 103-0', 'tier': 9, 'type': 'td'}, 
'S11_Strv_103B': {'short_name': 'Strv 103B', 'tier': 10, 'type': 'td'}, 
'S12_Strv_M40': {'short_name': 'Strv m/40L', 'tier': 3, 'type': 'light'}, 
'S13_Leo': {'short_name': 'Leo', 'tier': 7, 'type': 'medium'}, 
'S14_Ikv_103': {'short_name': 'Ikv 103', 'tier': 5, 'type': 'td'}, 
'S15_L_60': {'short_name': 'L-60', 'tier': 2, 'type': 'light'}, 
'S16_Kranvagn': {'short_name': 'Kranvagn', 'tier': 10, 'type': 'heavy'}, 
'S17_EMIL_1952_E2': {'short_name': 'Emil II', 'tier': 9, 'type': 'heavy'}, 
'S18_EMIL_1951_E1': {'short_name': 'Emil I', 'tier': 8, 'type': 'heavy'}, 
'S19_Sav_M43': {'short_name': 'Sav m/43', 'tier': 4, 'type': 'td'}, 
'S20_Ikv_72': {'short_name': 'Ikv 72', 'tier': 3, 'type': 'td'}, 
'S21_UDES_03': {'short_name': 'UDES 03', 'tier': 8, 'type': 'td'}, 
'S22_Strv_S1': {'short_name': 'Strv S1', 'tier': 8, 'type': 'td'}, 
'S23_Strv_81': {'short_name': 'Strv 81', 'tier': 8, 'type': 'medium'}, 
'S23_Strv_81_sabaton': {'short_name': 'P:Victoria', 'tier': 8, 'type': 'medium'},
'_105_leFH18B2': {'short_name': 'leFH18B2', 'tier': 5, 'type': 'light'}, 
'A115_Chrysler_K_GF': {'short_name': 'Chrysler GF', 'tier': 8, 'type': 'heavy'}, 
'A121_M26_Cologne': {'short_name': 'Eagle 7', 'tier': 7, 'type': 'medium'}, 
'A122_TS-5': {'short_name': 'TS-5', 'tier': 8, 'type': 'heavy'}, 
'A123_T78': {'short_name': 'T78', 'tier': 6, 'type': 'light'}, 
'A124_T54E2': {'short_name': 'Renegade', 'tier': 8, 'type': 'medium'}, 
'A125_AEP_1': {'short_name': 'AE Phase I', 'tier': 9, 'type': 'heavy'}, 
'A126_PzVI_Tiger_II_capt': {'short_name': 'King Tiger (C)', 'tier': 7, 'type': 'heavy'}, 
'A127_TL_1_LPC': {'short_name': 'TL-1 LPC', 'tier': 8, 'type': 'medium'}, 
'A130_Super_Hellcat': {'short_name': 'Super Hellcat', 'tier': 7, 'type': 'heavy'}, 
'A-20': {'short_name': 'A-20', 'tier': 4, 'type': 'light'}, 
'A-32': {'short_name': 'A-32', 'tier': 4, 'type': 'light'}, 
'A43': {'short_name': 'A-43', 'tier': 6, 'type': 'medium'}, 
'A44': {'short_name': 'A-44', 'tier': 7, 'type': 'medium'}, 
'AMX_105AM': {'short_name': 'AMX 13 AM', 'tier': 5, 'type': 'spg'}, 
'AMX_12t': {'short_name': 'AMX 12 t', 'tier': 6, 'type': 'light'}, 
'AMX_13_75': {'short_name': 'AMX 13 75', 'tier': 7, 'type': 'light'}, 
'AMX_13_90': {'short_name': 'AMX 13 90', 'tier': 9, 'type': 'light'}, 
'AMX_13F3AM': {'short_name': 'AMX 13 F3', 'tier': 6, 'type': 'spg'}, 
'AMX_50_100': {'short_name': 'AMX 50 100', 'tier': 8, 'type': 'heavy'}, 
'AMX_50_120': {'short_name': 'AMX 50 120', 'tier': 9, 'type': 'heavy'}, 
'AMX_50Fosh_155': {'short_name': 'Foch 155', 'tier': 10, 'type': 'td'}, 
'AMX_AC_Mle1946': {'short_name': 'AMX AC 46', 'tier': 7, 'type': 'heavy'}, 
'AMX_AC_Mle1948': {'short_name': 'AMX AC 48', 'tier': 8, 'type': 'heavy'}, 
'AMX_M4_1945': {'short_name': 'AMX M4 45', 'tier': 7, 'type': 'heavy'}, 
'AMX_Ob_Am105': {'short_name': 'AMX 105 AM', 'tier': 4, 'type': 'spg'}, 
'AMX38': {'short_name': 'AMX 38', 'tier': 3, 'type': 'light'}, 
'AMX40': {'short_name': 'AMX 40', 'tier': 4, 'type': 'light'}, 
'AMX50_Foch': {'short_name': 'Foch', 'tier': 9, 'type': 'heavy'}, 
'ARL_44': {'short_name': 'ARL 44', 'tier': 6, 'type': 'heavy'}, 
'ARL_V39': {'short_name': 'ARL V39', 'tier': 6, 'type': 'td'}, 
'AT-1': {'short_name': 'AT-1', 'tier': 2, 'type': 'light'}, 
'Auf_Panther': {'short_name': 'Aufkl.Panther', 'tier': 7, 'type': 'light'}, 
'B1': {'short_name': 'B1', 'tier': 4, 'type': 'heavy'}, 
'B-1bis_captured': {'short_name': 'Pz. B2', 'tier': 4, 'type': 'medium'}, 
'Bat_Chatillon155_55': {'short_name': 'B-C 155 55', 'tier': 9, 'type': 'spg'}, 
'Bat_Chatillon155_58': {'short_name': 'B-C 155 58', 'tier': 10, 'type': 'spg'}, 
'Bat_Chatillon25t': {'short_name': 'B-C 25 t', 'tier': 10, 'type': 'medium'}, 
'BDR_G1B': {'short_name': 'BDR G1 B', 'tier': 5, 'type': 'medium'}, 
'Bison_I': {'short_name': 'Bison', 'tier': 3, 'type': 'spg'}, 
'BT-2': {'short_name': 'BT-2', 'tier': 2, 'type': 'light'}, 
'BT-7': {'short_name': 'BT-7', 'tier': 3, 'type': 'light'}, 
'BT-SV': {'short_name': 'BT-SV', 'tier': 3, 'type': 'light'}, 
'Ch42_WalkerBulldog_M41D': {'short_name': 'M41D', 'tier': 8, 'type': 'light'}, 
'Chi_Ha': {'short_name': 'Chi-Ha', 'tier': 3, 'type': 'medium'}, 
'Chi_He': {'short_name': 'Chi-He', 'tier': 4, 'type': 'medium'}, 
'Chi_Ni': {'short_name': 'Chi-Ni', 'tier': 2, 'type': 'medium'}, 
'Chi_Nu': {'short_name': 'Chi-Nu', 'tier': 5, 'type': 'unknown'}, 
'Chi_Nu_Kai': {'short_name': 'Chi-Nu Kai', 'tier': 5, 'type': 'medium'}, 
'Chi_Ri': {'short_name': 'Chi-Ri', 'tier': 7, 'type': 'medium'}, 
'Chi_To': {'short_name': 'Chi-To', 'tier': 6, 'type': 'medium'}, 
'Churchill_LL': {'short_name': 'Churchill III', 'tier': 5, 'type': 'medium'}, 
'Cz13_T_27': {'short_name': 'Škoda T 27', 'tier': 8, 'type': 'light'}, 
'D1': {'short_name': 'D1', 'tier': 2, 'type': 'light'}, 
'D2': {'short_name': 'D2', 'tier': 3, 'type': 'medium'}, 
'DickerMax': {'short_name': 'Dicker Max', 'tier': 6, 'type': 'heavy'}, 
'DW_II': {'short_name': 'D.W. 2', 'tier': 4, 'type': 'heavy'}, 
'E-100': {'short_name': 'E 100', 'tier': 10, 'type': 'heavy'}, 
'E-25': {'short_name': 'E 25', 'tier': 7, 'type': 'light'}, 
'E-50': {'short_name': 'E 50', 'tier': 9, 'type': 'medium'}, 
'E50_Ausf_M': {'short_name': 'E 50 M', 'tier': 10, 'type': 'medium'}, 
'E-75': {'short_name': 'E 75', 'tier': 9, 'type': 'heavy'}, 
'ELC_AMX': {'short_name': 'AMX ELC bis', 'tier': 5, 'type': 'light'}, 
'F100_Panhard_EBR_90': {'short_name': 'EBR 90', 'tier': 9, 'type': 'light'}, 
'F106_Panhard_EBR_75_Mle1954': {'short_name': 'EBR 75 FL 10', 'tier': 8, 'type': 'light'}, 
'F107_Hotchkiss_EBR': {'short_name': 'EBR Hotch.', 'tier': 7, 'type': 'light'}, 
'F108_Panhard_EBR_105': {'short_name': 'EBR 105', 'tier': 10, 'type': 'light'}, 
'F109_AMD_Panhard_178B': {'short_name': 'AMD 178B', 'tier': 6, 'type': 'light'}, 
'F110_Lynx_6x6': {'short_name': 'Lynx 6x6', 'tier': 8, 'type': 'light'}, 
'F111_AM39_Gendron_Somua': {'short_name': 'AM Gendron', 'tier': 2, 'type': 'light'}, 
'F112_M10_RBFM': {'short_name': 'M10 RBFM', 'tier': 5, 'type': 'td'}, 
'F113_Bretagne_Panther': {'short_name': 'Bret. Panther', 'tier': 6, 'type': 'medium'}, 
'F42_AMR_35': {'short_name': 'AMR 35', 'tier': 2, 'type': 'light'}, 
'FCM_36Pak40': {'short_name': 'FCM36Pak40', 'tier': 3, 'type': 'td'}, 
'FCM_50t': {'short_name': 'FCM 50 t', 'tier': 8, 'type': 'medium'}, 
'Ferdinand': {'short_name': 'Ferdinand', 'tier': 8, 'type': 'heavy'}, 
'G_E': {'short_name': 'G.W. E 100', 'tier': 10, 'type': 'spg'}, 
'G_Panther': {'short_name': 'G.W. Panther', 'tier': 7, 'type': 'td'}, 
'G_Tiger': {'short_name': 'G.W. Tiger', 'tier': 9, 'type': 'spg'}, 
'G139_MKA': {'short_name': 'MKA', 'tier': 2, 'type': 'light'}, 
'G14_PzIII_A': {'short_name': 'Pz. III E', 'tier': 3, 'type': 'light'}, 
'G140_HWK_30': {'short_name': 'HWK 30', 'tier': 8, 'type': 'light'}, 
'G141_VK7501K': {'short_name': 'VK 75.01 K', 'tier': 8, 'type': 'heavy'}, 
'G142_M48RPz': {'short_name': 'M48 RPz', 'tier': 8, 'type': 'medium'}, 
'G143_E75_TS': {'short_name': 'E 75 TS', 'tier': 8, 'type': 'heavy'}, 
'GAZ-74b': {'short_name': 'SU-85B', 'tier': 4, 'type': 'td'}, 
'GB100_Manticore': {'short_name': 'Manticore', 'tier': 10, 'type': 'light'}, 
'GB101_FV1066_Senlac': {'short_name': 'Senlac', 'tier': 8, 'type': 'light'}, 
'GB102_LHMTV': {'short_name': 'LHMTV', 'tier': 8, 'type': 'light'}, 
'GB103_GSOR3301_AVR_FS': {'short_name': 'GSOR', 'tier': 9, 'type': 'light'}, 
'GB104_GSR_3301_Setter': {'short_name': 'Setter', 'tier': 7, 'type': 'light'}, 
'GB25_Loyd_Carrier': {'short_name': 'Loyd GC', 'tier': 2, 'type': 'spg'}, 
'GB94_Centurion_Mk5-1_RAAC': {'short_name': 'Centurion 5/1', 'tier': 8, 'type': 'medium'}, 
'GB95_Ekins_Firefly_M4A4': {'short_name': 'Firefly VC', 'tier': 6, 'type': 'medium'}, 
'GB96_Excalibur': {'short_name': 'Excalibur', 'tier': 6, 'type': 'td'}, 
'GB97_Chimera': {'short_name': 'Chimera', 'tier': 8, 'type': 'medium'}, 
'GB98_T95_FV4201_Chieftain': {'short_name': 'T95/FV4201', 'tier': 10, 'type': 'medium'}, 
'GB99_Turtle_Mk1': {'short_name': 'Turtle I', 'tier': 8, 'type': 'td'}, 
'Grille': {'short_name': 'Grille', 'tier': 5, 'type': 'spg'}, 
'GW_Mk_VIe': {'short_name': 'G.Pz. Mk. VI', 'tier': 2, 'type': 'spg'}, 
'GW_Tiger_P': {'short_name': 'G.W. Tiger P', 'tier': 8, 'type': 'spg'}, 
'H39_captured': {'short_name': 'Pz. 38H', 'tier': 2, 'type': 'light'}, 
'Ha_Go': {'short_name': 'Ha-Go', 'tier': 2, 'type': 'light'}, 
'Hetzer': {'short_name': 'Hetzer', 'tier': 4, 'type': 'td'}, 
'Hotchkiss_H35': {'short_name': 'H35', 'tier': 2, 'type': 'light'}, 
'Hummel': {'short_name': 'Hummel', 'tier': 6, 'type': 'heavy'}, 
'Indien_Panzer': {'short_name': 'Indien-Pz.', 'tier': 8, 'type': 'medium'}, 
'IS': {'short_name': 'IS', 'tier': 7, 'type': 'heavy'}, 
'IS-3': {'short_name': 'IS-3', 'tier': 8, 'type': 'heavy'}, 
'IS-4': {'short_name': 'IS-4', 'tier': 10, 'type': 'heavy'}, 
'IS-7': {'short_name': 'IS-7', 'tier': 10, 'type': 'heavy'}, 
'ISU-152': {'short_name': 'ISU-152', 'tier': 8, 'type': 'td'}, 
'It03_M15_42': {'short_name': 'M15/42', 'tier': 3, 'type': 'medium'}, 
'It04_Fiat_3000': {'short_name': 'Fiat 3000', 'tier': 1, 'type': 'light'}, 
'It05_Carro_L6_40': {'short_name': 'L6/40', 'tier': 2, 'type': 'light'}, 
'It06_M14_41': {'short_name': 'M14/41', 'tier': 2, 'type': 'medium'}, 
'It07_P26_40': {'short_name': 'P26/40', 'tier': 4, 'type': 'medium'}, 
'It08_Progetto_M40_mod_65': {'short_name': 'Progetto 65', 'tier': 10, 'type': 'medium'}, 
'It10_P43_bis': {'short_name': 'P.43 bis', 'tier': 6, 'type': 'medium'}, 
'It11_P43': {'short_name': 'P.43', 'tier': 5, 'type': 'medium'}, 
'It12_Prototipo_Standard_B': {'short_name': 'Standard B', 'tier': 9, 'type': 'medium'}, 
'It14_P44_Pantera': {'short_name': 'P.44 Pantera', 'tier': 8, 'type': 'medium'}, 
'JagdPanther': {'short_name': 'JPanther', 'tier': 7, 'type': 'td'}, 
'JagdPantherII': {'short_name': 'JPanther II', 'tier': 8, 'type': 'td'}, 
'JagdPz_E100': {'short_name': 'Jg.Pz. E 100', 'tier': 10, 'type': 'td'}, 
'JagdPzIV': {'short_name': 'Jg.Pz. IV', 'tier': 6, 'type': 'medium'}, 
'JagdTiger': {'short_name': 'Jagdtiger', 'tier': 9, 'type': 'heavy'}, 
'JagdTiger_SdKfz_185': {'short_name': 'JgTig.8,8 cm', 'tier': 8, 'type': 'td'}, 
'Ke_Ho': {'short_name': 'Ke-Ho', 'tier': 4, 'type': 'light'}, 
'Ke_Ni': {'short_name': 'Ke-Ni', 'tier': 3, 'type': 'light'}, 
'KV1': {'short_name': 'KV-1', 'tier': 5, 'type': 'medium'}, 
'KV-13': {'short_name': 'KV-13', 'tier': 7, 'type': 'medium'}, 
'KV-1s': {'short_name': 'KV-1S', 'tier': 5, 'type': 'heavy'}, 
'KV2': {'short_name': 'KV-2', 'tier': 6, 'type': 'heavy'}, 
'KV-220': {'short_name': 'KV-220-2 T', 'tier': 5, 'type': 'heavy'}, 
'KV-220_action': {'short_name': 'KV-220-2', 'tier': 5, 'type': 'heavy'}, 
'KV-3': {'short_name': 'KV-3', 'tier': 7, 'type': 'heavy'}, 
'KV4': {'short_name': 'KV-4', 'tier': 8, 'type': 'heavy'}, 
'KV-5': {'short_name': 'KV-5', 'tier': 8, 'type': 'medium'}, 
'Leopard1': {'short_name': 'Leopard 1', 'tier': 10, 'type': 'medium'}, 
'Lorraine155_50': {'short_name': 'Lorr. 155 50', 'tier': 7, 'type': 'spg'}, 
'Lorraine155_51': {'short_name': 'Lorr. 155 51', 'tier': 8, 'type': 'spg'}, 
'Lorraine39_L_AM': {'short_name': 'Lorr. 39L AM', 'tier': 3, 'type': 'spg'}, 
'Lorraine40t': {'short_name': 'Lorr. 40 t', 'tier': 8, 'type': 'medium'}, 
'Lowe': {'short_name': 'Löwe', 'tier': 8, 'type': 'heavy'}, 
'LTP': {'short_name': 'LTP', 'tier': 3, 'type': 'light'}, 
'Ltraktor': {'short_name': 'L.Tr.', 'tier': 1, 'type': 'light'}, 
'M10_Wolverine': {'short_name': 'Wolverine', 'tier': 5, 'type': 'medium'}, 
'M103': {'short_name': 'M103', 'tier': 9, 'type': 'heavy'}, 
'M12': {'short_name': 'M12', 'tier': 7, 'type': 'spg'}, 
'M18_Hellcat': {'short_name': 'Hellcat', 'tier': 6, 'type': 'td'}, 
'M2_lt': {'short_name': 'M2 Light', 'tier': 2, 'type': 'light'}, 
'M2_med': {'short_name': 'M2 Medium', 'tier': 3, 'type': 'medium'}, 
'M22_Locust': {'short_name': 'Locust', 'tier': 3, 'type': 'light'}, 
'M24_Chaffee': {'short_name': 'Chaffee', 'tier': 5, 'type': 'light'}, 
'M3_Grant': {'short_name': 'M3 Lee', 'tier': 4, 'type': 'medium'}, 
'M3_Stuart': {'short_name': 'M3 Stuart', 'tier': 3, 'type': 'light'}, 
'M3_Stuart_LL': {'short_name': 'M3 Light', 'tier': 3, 'type': 'light'}, 
'M36_Slagger': {'short_name': 'Jackson', 'tier': 6, 'type': 'medium'}, 
'M37': {'short_name': 'M37', 'tier': 4, 'type': 'light'}, 
'M4_Sherman': {'short_name': 'M4A1', 'tier': 5, 'type': 'medium'}, 
'M40M43': {'short_name': 'M40/M43', 'tier': 8, 'type': 'medium'}, 
'M41': {'short_name': 'M41 HMC', 'tier': 5, 'type': 'spg'}, 
'M41_Bulldog': {'short_name': 'M41 Bulldog', 'tier': 8, 'type': 'light'}, 
'M44': {'short_name': 'M44', 'tier': 6, 'type': 'light'}, 
'M46_Patton': {'short_name': 'M46 Patton', 'tier': 9, 'type': 'medium'}, 
'M4A2E4': {'short_name': 'M4A2E4', 'tier': 5, 'type': 'medium'}, 
'M4A3E8_Sherman': {'short_name': 'M4A3E8', 'tier': 6, 'type': 'medium'}, 
'M5_Stuart': {'short_name': 'M5 Stuart', 'tier': 4, 'type': 'light'}, 
'M53_55': {'short_name': 'M53/M55', 'tier': 9, 'type': 'medium'}, 
'M6': {'short_name': 'M6', 'tier': 6, 'type': 'light'}, 
'M60': {'short_name': 'M60', 'tier': 10, 'type': 'medium'}, 
'M6A2E1': {'short_name': 'M6A2E1', 'tier': 8, 'type': 'heavy'}, 
'M7_med': {'short_name': 'M7', 'tier': 5, 'type': 'light'}, 
'M7_Priest': {'short_name': 'M7 Priest', 'tier': 3, 'type': 'spg'}, 
'M8A1': {'short_name': 'M8A1', 'tier': 4, 'type': 'light'}, 
'Marder_III': {'short_name': 'Marder 38T', 'tier': 4, 'type': 'td'}, 
'Matilda_II_LL': {'short_name': 'Matilda IV', 'tier': 5, 'type': 'medium'}, 
'Maus': {'short_name': 'Maus', 'tier': 10, 'type': 'heavy'}, 
'MS-1': {'short_name': 'MS-1', 'tier': 1, 'type': 'light'}, 
'MT25': {'short_name': 'MT-25', 'tier': 6, 'type': 'light'}, 
'Nashorn': {'short_name': 'Nashorn', 'tier': 6, 'type': 'td'}, 
'NC27': {'short_name': 'R. Otsu', 'tier': 1, 'type': 'light'}, 
'Object_140': {'short_name': 'Obj. 140', 'tier': 10, 'type': 'medium'}, 
'Object_212': {'short_name': '212A', 'tier': 9, 'type': 'spg'}, 
'Object_261': {'short_name': 'Obj. 261', 'tier': 10, 'type': 'spg'}, 
'Object_430': {'short_name': 'Obj. 430', 'tier': 9, 'type': 'medium'}, 
'Object_704': {'short_name': 'Obj. 704', 'tier': 9, 'type': 'td'}, 
'Object_907': {'short_name': 'Obj. 907', 'tier': 10, 'type': 'medium'}, 
'Object252': {'short_name': 'IS-6', 'tier': 8, 'type': 'heavy'}, 
'Object263': {'short_name': 'Obj. 263', 'tier': 9, 'type': 'heavy'}, 
'Object268': {'short_name': 'Obj. 268', 'tier': 10, 'type': 'heavy'}, 
'Object416': {'short_name': 'Obj. 416', 'tier': 8, 'type': 'medium'}, 
'Panther_II': {'short_name': 'Panther II', 'tier': 8, 'type': 'medium'}, 
'Panther_M10': {'short_name': 'Panther/M10', 'tier': 7, 'type': 'medium'}, 
'PanzerJager_I': {'short_name': 'Pz.Jäg. I', 'tier': 2, 'type': 'td'}, 
'Pershing': {'short_name': 'Pershing', 'tier': 8, 'type': 'medium'}, 
'Pl01_TKS_20mm': {'short_name': 'TKS 20', 'tier': 2, 'type': 'light'}, 
'Pl05_50TP_Tyszkiewicza': {'short_name': '50TP', 'tier': 9, 'type': 'heavy'}, 
'Pl06_10TP': {'short_name': '10TP', 'tier': 3, 'type': 'light'}, 
'Pl07_14TP': {'short_name': '14TP', 'tier': 4, 'type': 'light'}, 
'Pl08_50TP_prototyp': {'short_name': '50TP pr.', 'tier': 8, 'type': 'heavy'}, 
'Pl08_Czolg_T_wz51': {'short_name': '50TP prototyp', 'tier': 8, 'type': 'heavy'}, 
'Pl09_7TP': {'short_name': '7TP', 'tier': 2, 'type': 'light'}, 
'Pl10_40TP_Habicha': {'short_name': '40TP', 'tier': 6, 'type': 'medium'}, 
'Pl11_45TP_Habicha': {'short_name': '45TP', 'tier': 7, 'type': 'medium'}, 
'Pl12_25TP_KSUST_II': {'short_name': '25TP', 'tier': 5, 'type': 'medium'}, 
'Pl13_53TP_Markowskiego': {'short_name': '53TP', 'tier': 8, 'type': 'heavy'}, 
'Pl14_4TP': {'short_name': '4TP', 'tier': 1, 'type': 'light'}, 
'Pl15_60TP_Lewandowskiego': {'short_name': '60TP', 'tier': 10, 'type': 'heavy'}, 
'Pl16_T34_85_Rudy': {'short_name': 'Rudy Pl', 'tier': 6, 'type': 'medium'}, 
'Pro_Ag_A': {'short_name': 'Leopard PT A', 'tier': 9, 'type': 'medium'}, 
'Pz_II_AusfG': {'short_name': 'Pz. II G', 'tier': 3, 'type': 'light'}, 
'Pz_IV_AusfA': {'short_name': 'Pz. IV A', 'tier': 3, 'type': 'medium'}, 
'Pz_IV_AusfD': {'short_name': 'Pz. IV D', 'tier': 4, 'type': 'medium'}, 
'Pz_IV_AusfH': {'short_name': 'Pz. IV H', 'tier': 5, 'type': 'medium'}, 
'Pz_Sfl_IVb': {'short_name': 'Pz.Sfl. IVb', 'tier': 4, 'type': 'spg'}, 
'Pz_Sfl_IVc': {'short_name': 'Pz.Sfl. IVc', 'tier': 5, 'type': 'td'}, 
'Pz35t': {'short_name': 'Pz. 35 (t)', 'tier': 2, 'type': 'light'}, 
'Pz38_NA': {'short_name': 'Pz. 38 nA', 'tier': 4, 'type': 'light'}, 
'Pz38t': {'short_name': 'Pz. 38 (t)', 'tier': 3, 'type': 'light'}, 
'PzI': {'short_name': 'Pz. I', 'tier': 2, 'type': 'light'}, 
'PzI_ausf_C': {'short_name': 'Pz. I C', 'tier': 3, 'type': 'light'}, 
'PzII': {'short_name': 'Pz. II', 'tier': 2, 'type': 'light'}, 
'PzII_J': {'short_name': 'Pz. II J', 'tier': 3, 'type': 'light'}, 
'PzII_Luchs': {'short_name': 'Luchs', 'tier': 4, 'type': 'light'}, 
'PzIII_A': {'short_name': 'Pz. III E', 'tier': 3, 'type': 'light'}, 
'PzIII_AusfJ': {'short_name': 'Pz. III J', 'tier': 4, 'type': 'medium'}, 
'PzIII_IV': {'short_name': 'Pz. III/IV', 'tier': 5, 'type': 'medium'}, 
'PzIV': {'short_name': 'Pz. IV', 'tier': 5, 'type': 'medium'}, 
'PzIV_Hydro': {'short_name': 'Pz. IV hydr.', 'tier': 5, 'type': 'medium'}, 
'PzIV_schmalturm': {'short_name': 'Pz. IV S.', 'tier': 6, 'type': 'medium'}, 
'PzV': {'short_name': 'Panther', 'tier': 7, 'type': 'medium'}, 
'PzV_PzIV': {'short_name': 'Pz. V/IV', 'tier': 5, 'type': 'medium'}, 
'PzV_PzIV_ausf_Alfa': {'short_name': 'Pz. V/IV A', 'tier': 5, 'type': 'medium'}, 
'PzVI': {'short_name': 'Tiger I', 'tier': 7, 'type': 'heavy'}, 
'PzVI_Tiger_P': {'short_name': 'Tiger (P)', 'tier': 7, 'type': 'heavy'}, 
'PzVIB_Tiger_II': {'short_name': 'Tiger II', 'tier': 8, 'type': 'heavy'}, 
'R127_T44_100_U': {'short_name': 'Т-44-100 (У)', 'tier': 8, 'type': 'medium'}, 
'R139_IS_M': {'short_name': 'IS-M', 'tier': 8, 'type': 'heavy'}, 
'R144_K_91': {'short_name': 'K-91', 'tier': 10, 'type': 'medium'}, 
'R152_KV2_W': {'short_name': 'KV-2 (R)', 'tier': 6, 'type': 'heavy'}, 
'R154_T_34E_1943': {'short_name': 'T-34S', 'tier': 5, 'type': 'medium'}, 
'R155_Object_277': {'short_name': 'Obj. 277', 'tier': 10, 'type': 'heavy'}, 
'R156_IS_2M': {'short_name': 'IS-2M', 'tier': 7, 'type': 'heavy'}, 
'R157_Object_279R': {'short_name': 'Obj. 279 (e)', 'tier': 10, 'type': 'heavy'}, 
'R158_LT_432': {'short_name': 'LT-432', 'tier': 8, 'type': 'light'}, 
'R159_SU_130PM': {'short_name': 'SU-130PM', 'tier': 8, 'type': 'td'}, 
'R160_T_50_2': {'short_name': 'T-50-2', 'tier': 6, 'type': 'light'}, 
'R161_T_116': {'short_name': 'T-116', 'tier': 3, 'type': 'light'}, 
'R169_ST_II': {'short_name': 'ST-II', 'tier': 10, 'type': 'heavy'}, 
'R170_IS_2_II': {'short_name': 'IS-2-II', 'tier': 8, 'type': 'heavy'}, 
'R171_IS_3_II': {'short_name': 'IS-3-II', 'tier': 9, 'type': 'heavy'}, 
'R38_KV-220_action': {'short_name': 'KV-220-2', 'tier': 5, 'type': 'heavy'}, 
'Ram-II': {'short_name': 'Ram II', 'tier': 5, 'type': 'medium'}, 
'RenaultBS': {'short_name': 'FT BS', 'tier': 2, 'type': 'spg'}, 
'RenaultFT': {'short_name': 'FT', 'tier': 1, 'type': 'light'}, 
'RenaultFT_AC': {'short_name': 'FT AC', 'tier': 2, 'type': 'td'}, 
'RenaultUE57': {'short_name': 'UE 57', 'tier': 3, 'type': 'td'}, 
'RhB_Waffentrager': {'short_name': 'Rhm.-B. WT', 'tier': 8, 'type': 'td'}, 
'S_35CA': {'short_name': 'S35 CA', 'tier': 5, 'type': 'td'}, 
'S25_EMIL_51': {'short_name': 'EMIL 1951', 'tier': 8, 'type': 'heavy'}, 
'S26_Lansen_C': {'short_name': 'Lansen C', 'tier': 8, 'type': 'medium'}, 
'S27_UDES_16': {'short_name': 'UDES 16', 'tier': 9, 'type': 'medium'}, 
'S28_UDES_15_16': {'short_name': 'UDES 15/16', 'tier': 10, 'type': 'medium'}, 
'S29_UDES_14_5': {'short_name': 'UDES 14 5', 'tier': 8, 'type': 'medium'}, 
'S35_captured': {'short_name': 'Pz. S35', 'tier': 3, 'type': 'medium'}, 
'S-51': {'short_name': 'S-51', 'tier': 7, 'type': 'spg'}, 
'Sexton_I': {'short_name': 'nan', 'tier': 3, 'type': 'spg'}, 
'Sherman_Jumbo': {'short_name': 'M4A3E2', 'tier': 6, 'type': 'medium'}, 
'Somua_Sau_40': {'short_name': 'SAu 40', 'tier': 4, 'type': 'td'}, 
'ST_B1': {'short_name': 'STB-1', 'tier': 10, 'type': 'medium'}, 
'ST_I': {'short_name': 'ST-I', 'tier': 9, 'type': 'heavy'}, 
'STA_1': {'short_name': 'STA-1', 'tier': 8, 'type': 'medium'}, 
'StuG_40_AusfG': {'short_name': 'StuG III G', 'tier': 5, 'type': 'medium'}, 
'Sturer_Emil': {'short_name': 'St. Emil', 'tier': 7, 'type': 'heavy'}, 
'Sturmpanzer_II': {'short_name': 'St.Pz. II', 'tier': 4, 'type': 'spg'}, 
'SU_85I': {'short_name': 'SU-85I', 'tier': 5, 'type': 'td'}, 
'SU-100': {'short_name': 'SU-100', 'tier': 6, 'type': 'heavy'}, 
'SU100M1': {'short_name': 'SU-100M1', 'tier': 7, 'type': 'td'}, 
'SU100Y': {'short_name': 'SU-100Y', 'tier': 6, 'type': 'heavy'}, 
'SU-101': {'short_name': 'SU-101', 'tier': 8, 'type': 'td'}, 
'SU122_44': {'short_name': 'SU-122-44', 'tier': 7, 'type': 'td'}, 
'SU122A': {'short_name': 'SU-122A', 'tier': 5, 'type': 'spg'}, 
'SU-14': {'short_name': 'SU-14-2', 'tier': 8, 'type': 'spg'}, 
'SU14_1': {'short_name': 'SU-14-1', 'tier': 7, 'type': 'spg'}, 
'SU-152': {'short_name': 'SU-152', 'tier': 7, 'type': 'heavy'}, 
'SU-18': {'short_name': 'SU-18', 'tier': 2, 'type': 'spg'}, 
'SU-26': {'short_name': 'SU-26', 'tier': 3, 'type': 'spg'}, 
'SU-5': {'short_name': 'SU-5', 'tier': 4, 'type': 'light'}, 
'SU-76': {'short_name': 'SU-76M', 'tier': 3, 'type': 'td'}, 
'SU76I': {'short_name': 'SU-76I', 'tier': 3, 'type': 'td'}, 
'SU-8': {'short_name': 'SU-8', 'tier': 6, 'type': 'spg'}, 
'SU-85': {'short_name': 'SU-85', 'tier': 5, 'type': 'medium'}, 
'T1_Cunningham': {'short_name': 'T1', 'tier': 1, 'type': 'light'}, 
'T1_E6': {'short_name': 'T1E6', 'tier': 2, 'type': 'light'}, 
'T1_hvy': {'short_name': 'T1 Heavy', 'tier': 5, 'type': 'medium'}, 
'T110E3': {'short_name': 'T110E3', 'tier': 10, 'type': 'heavy'}, 
'T110E4': {'short_name': 'T110E4', 'tier': 10, 'type': 'heavy'}, 
'T-127': {'short_name': 'T-127', 'tier': 3, 'type': 'light'}, 
'T14': {'short_name': 'T14', 'tier': 5, 'type': 'heavy'}, 
'T-15': {'short_name': 'Pz. T 15', 'tier': 3, 'type': 'light'}, 
'T150': {'short_name': 'T-150', 'tier': 6, 'type': 'heavy'}, 
'T18': {'short_name': 'T18', 'tier': 3, 'type': 'light'}, 
'T2_lt': {'short_name': 'T2 Light', 'tier': 2, 'type': 'light'}, 
'T2_med': {'short_name': 'T2 Medium', 'tier': 2, 'type': 'medium'}, 
'T20': {'short_name': 'T20', 'tier': 7, 'type': 'medium'}, 
'T21': {'short_name': 'T21', 'tier': 6, 'type': 'light'}, 
'T23E3': {'short_name': 'T23E3', 'tier': 7, 'type': 'medium'}, 
'T-25': {'short_name': 'Pz. T 25', 'tier': 5, 'type': 'light'}, 
'T25_2': {'short_name': 'T25/2', 'tier': 7, 'type': 'td'}, 
'T25_AT': {'short_name': 'T25 AT', 'tier': 7, 'type': 'td'}, 
'T-26': {'short_name': 'T-26', 'tier': 2, 'type': 'light'}, 
'T26_E4_SuperPershing': {'short_name': 'T26E4', 'tier': 8, 'type': 'medium'}, 
'T28': {'short_name': 'T28', 'tier': 8, 'type': 'medium'}, 
'T-28': {'short_name': 'T-28', 'tier': 4, 'type': 'medium'}, 
'T28_Prototype': {'short_name': 'T28 Prot.', 'tier': 8, 'type': 'heavy'}, 
'T29': {'short_name': 'T29', 'tier': 7, 'type': 'heavy'}, 
'T30': {'short_name': 'T30', 'tier': 9, 'type': 'heavy'}, 
'T32': {'short_name': 'T32', 'tier': 8, 'type': 'light'}, 
'T-34': {'short_name': 'T-34', 'tier': 5, 'type': 'medium'}, 
'T34_hvy': {'short_name': 'T34', 'tier': 8, 'type': 'heavy'}, 
'T-34-85': {'short_name': 'T-34-85', 'tier': 6, 'type': 'medium'}, 
'T37': {'short_name': 'T37', 'tier': 6, 'type': 'light'}, 
'T40': {'short_name': 'T40', 'tier': 4, 'type': 'td'}, 
'T-43': {'short_name': 'T-43', 'tier': 7, 'type': 'medium'}, 
'T-44': {'short_name': 'T-44', 'tier': 8, 'type': 'medium'}, 
'T-46': {'short_name': 'T-46', 'tier': 3, 'type': 'light'}, 
'T49': {'short_name': 'T49', 'tier': 9, 'type': 'light'}, 
'T-50': {'short_name': 'T-50', 'tier': 5, 'type': 'light'}, 
'T-54': {'short_name': 'T-54', 'tier': 9, 'type': 'medium'}, 
'T54E1': {'short_name': 'T54E1', 'tier': 9, 'type': 'medium'}, 
'T57_58': {'short_name': 'T57 Heavy', 'tier': 10, 'type': 'heavy'}, 
'T-60': {'short_name': 'T-60', 'tier': 2, 'type': 'light'}, 
'T62A': {'short_name': 'T-62A', 'tier': 10, 'type': 'medium'}, 
'T67': {'short_name': 'T67', 'tier': 5, 'type': 'td'}, 
'T69': {'short_name': 'T69', 'tier': 8, 'type': 'medium'}, 
'T7_Combat_Car': {'short_name': 'T7 Car', 'tier': 2, 'type': 'light'}, 
'T-70': {'short_name': 'T-70', 'tier': 3, 'type': 'light'}, 
'T71': {'short_name': 'T71 DA', 'tier': 7, 'type': 'light'}, 
'T80': {'short_name': 'T-80', 'tier': 4, 'type': 'light'}, 
'T82': {'short_name': 'T82', 'tier': 4, 'type': 'spg'}, 
'T92': {'short_name': 'T92 HMC', 'tier': 10, 'type': 'spg'}, 
'T95': {'short_name': 'T95', 'tier': 9, 'type': 'td'}, 
'T95_E2': {'short_name': 'T95E2', 'tier': 8, 'type': 'medium'}, 
'T95_E6': {'short_name': 'T95E6', 'tier': 10, 'type': 'medium'}, 
'Te_Ke': {'short_name': 'Te-Ke', 'tier': 2, 'type': 'light'}, 
'Tetrarch_LL': {'short_name': 'Tetrarch', 'tier': 2, 'type': 'light'}, 
'Type_61': {'short_name': 'Type 61', 'tier': 9, 'type': 'medium'}, 
'Valentine_LL': {'short_name': 'Valentine II', 'tier': 4, 'type': 'light'}, 
'VK1602': {'short_name': 'Leopard', 'tier': 5, 'type': 'light'}, 
'VK2001DB': {'short_name': 'VK 20.01 D', 'tier': 4, 'type': 'medium'}, 
'VK2801': {'short_name': 'VK 28.01', 'tier': 6, 'type': 'light'}, 
'VK3001H': {'short_name': 'VK 30.01 H', 'tier': 5, 'type': 'heavy'}, 
'VK3001P': {'short_name': 'VK 30.01 P', 'tier': 6, 'type': 'medium'}, 
'VK3002DB': {'short_name': 'VK 30.02 D', 'tier': 7, 'type': 'medium'}, 
'VK3002DB_V1': {'short_name': 'VK 30.01 D', 'tier': 6, 'type': 'medium'}, 
'VK3002M': {'short_name': 'VK 30.02 M', 'tier': 6, 'type': 'medium'}, 
'VK3601H': {'short_name': 'VK 36.01 H', 'tier': 6, 'type': 'medium'}, 
'VK4502A': {'short_name': 'VK 45.02 A', 'tier': 8, 'type': 'heavy'}, 
'VK4502P': {'short_name': 'VK 45.02 B', 'tier': 9, 'type': 'heavy'}, 
'VK7201': {'short_name': 'VK 72.01 K', 'tier': 10, 'type': 'heavy'}, 
'Waffentrager_E100': {'short_name': 'WT E 100', 'tier': 10, 'type': 'td'}, 
'Waffentrager_IV': {'short_name': 'WT auf Pz. IV', 'tier': 9, 'type': 'td'}, 
'Wespe': {'short_name': 'Wespe', 'tier': 3, 'type': 'spg'}}

vehicle_types = (
    'Light Tanks',
    'Medium Tanks',
    'Heavy Tanks',
    'Tank Destroyers',
    'Artillery'
)

vehicle_types_data = {
    'Light Tanks':'light',
    'Medium Tanks':'medium',
    'Heavy Tanks':'heavy',
    'Tank Destroyers':'td',
    'Artillery':'spg'}

map_names = (
'Abbey',
'Airfield',
'Arctic Region',
'Cliff',
'El-Hallouf',
'Ensk',
'Erlenberg',
"Fisherman's Bay",
'Fjords',
'Highway',
'Himmelsdorf',
'Karelia',
#'Komarin',
'Lakeville',
'Live Oaks',
'Malinovka',
'Mines',
'Mountain Pass',
'Murovanka',
'Prokhorovka',
#'Province',
'Redshire',
'Ruinberg',
#'Sand River',
'Serene Coast',
#'Dragon Ridge',
'Siegfried Line',
#'South Coast',
'Steppes',
#'Swamp',
'Westfield',
#'Widepark'
)

maps_data = {
'Karelia' : '01_karelia',
'Malinovka' : '02_malinovka',
'Province' : '03_campania',
'Himmelsdorf' : '04_himmelsdorf',
'Prokhorovka' : '05_prohorovka',
'Ensk' : '06_ensk',
'Lakeville' : '07_lakeville',
'Ruinberg' : '08_ruinberg',
'Mines' : '10_hills',
'Murovanka' : '11_murovanka',
'Erlenberg' : '13_erlenberg',
'Siegfried Line' : '14_siegfried_line',
'Komarin' : '15_komarin',
'Widepark' : '17_munchen',
'Cliff' : '18_cliff',
'Abbey' : '19_monastery',
'Swamp' : '22_slough',
'Westfield' : '23_westfeld',
'Sand River' : '28_desert',
'El-Hallouf' : '29_el_hallouf',
'Airfield' : '31_airfield', 
'Fjords' : '33_fjord',
'Redshire' : '34_redshire',
'Steppes' : '35_steppes',
'Fisherman\'s Bay' : '36_fishing_bay',
'Mountain Pass' : '37_caucasus',
'Arctic Region' : '38_mannerheim_line',
'South Coast' : '39_crimea',
'Live Oaks' : '44_north_america',
'Highway' : '45_north_america',
'Serene Coast' : '47_canada_a',
'Dragon Ridge' : '51_asia'}
