
map_names = (
'Abbey',
'Airfield',
'Arctic Region',
'Cliff',
'El-Hallouf',
'Ensk',
'Erlenberg',
"Fisherman's Bay",
'Fjords',
'Highway',
'Himmelsdorf',
'Karelia',
'Komarin',
'Lakeville',
'Live Oaks',
'Malinovka',
'Mines',
'Mountain Pass',
'Murovanka',
'Prokhorovka',
'Province',
'Redshire',
'Ruinberg',
'Sand River',
'Serene CoastDragon Ridge',
'Siegfried Line',
'South Coast',
'Steppes',
'Swamp',
'Westfield',
'Widepark')

maps = {
'Karelia' : '01_karelia',
'Malinovka' : '02_malinovka',
'Province' : '03_campania',
'Himmelsdorf' : '04_himmelsdorf',
'Prokhorovka' : '05_prohorovka',
'Ensk' : '06_ensk',
'Lakeville' : '07_lakeville',
'Ruinberg' : '08_ruinberg',
'Mines' : '10_hills',
'Murovanka' : '11_murovanka',
'Erlenberg' : '13_erlenberg',
'Siegfried Line' : '14_siegfried_line',
'Komarin' : '15_komarin',
'Widepark' : '17_munchen',
'Cliff' : '18_cliff',
'Abbey' : '19_monastery',
'Swamp' : '22_slough',
'Westfield' : '23_westfeld',
'Sand River' : '28_desert',
'El-Hallouf' : '29_el_hallouf',
'Airfield' : '31_airfield', 
'Fjords' : '33_fjord',
'Redshire' : '34_redshire',
'Steppes' : '35_steppes',
'Fisherman\'s Bay' : '36_fishing_bay',
'Mountain Pass' : '37_caucasus',
'Arctic Region' : '38_mannerheim_line',
'South Coast' : '39_crimea',
'Live Oaks' : '44_north_america',
'Highway' : '45_north_america',
'Serene Coast' : '47_canada_a',
'Dragon Ridge' : '51_asia'}
